<?php defined('BASEPATH') OR exit('No direct script access allowed');
/**
 * Fichier de langue française pour Pancake App
 *
 * @author Anas AIT ALI (http://www.anas10.fr)
 * @author Marc-André Vaillancourt (http://www.webmarksolutions.ca) <divplus@gmail.com>
 * @link https://github.com/ahouin/pancake-translations
 * @copyright Copyright (c) 2010-2014, Pancake Payments
 * @license http://pancakeapp.com/license
 * @since 1.0
 * @version 2014-04-10
 */

// ------------------------------------------------------------------------

$lang = array(

    /** Mots globaux **/
    'global:overview' => 'Vue d\'ensemble',
    'global:error' => 'Erreur',
    'global:pancakeby7am' => 'Pancake :1',
    'global:allrelatedmediacopyright' => 'Pancake et tous les médias liés sont sous copyright :1 :2',
    'global:insecure_action' => 'Une action non sécurisé a été interceptée',
    'global:disabled_in_demo' => 'Certaines fonctionnalités de cette page sont désactivées pour la démo.',
    'global:estimates' => 'Devis',
    'global:estimate' => 'Devis',
    'global:incomplete_tasks' => 'Tâches incomplètes',
    'global:completed_tasks' => 'Tâches achevées',
    'global:projects' => 'Projets',
    'global:tickets' => 'Billets',
    'global:project' => 'Projet',
    'global:upload_failed' => 'Il y a eu un problème pour télécharger votre fichier. Veuillez réessayer. Si le problème persiste , s\'il vous plaît contacter support@pancakeapp.com.',
    'global:upload_not_allowed' => 'Le type de fichier du ficher que vous tentez de télécharger n\'est pas autorisé. Si vous avez besoin de télécharger un fichier de ce type , s\'il vous plaît compressez-le dans une archive .zip ou tout autre format archive que vous trouverez approprié.',
    'global:copied' => 'Copié',
    'global:sentbutunpaid' => 'Envoyé mais non payé',
    'global:task' => 'Tâche',
    'global:clients' => 'Clients',
    'global:access_denied' => "Accès refusé",
    'global:users' => 'Utilisateurs',
    'global:send_to_client' => 'Envoyer au client',
    'global:couldnotsendemail' => 'Impossible d\'envoyer l\'e-mail. S\'il vous plaît vérifier vos paramètres.',
    'global:emailsent' => 'Votre courriel a été envoyé!',
    'global:yes' => 'Oui',
    'global:no' => 'Non',
    'global:notyetsent' => 'Pas encore envoyé au client',
    'global:dontshowagain' => "Ne plus afficher ce message",
    'global:enable' => 'Activer',
    'global:is_enabled' => 'Activé',
    'global:is_completed' => 'Terminé',
    'global:Y' => 'O',
    'global:N' => 'N',
    'global:notes' => 'Notes',
    'global:description' => 'Description',
    'global:backtoadmin' => 'Retour dans la partie Admin',
    'global:type' => 'Type',
    'global:name' => 'Nom complet',
    'global:first_name' => 'Prénom',
    'global:last_name' => 'Nom',
    'global:company' => 'Entreprise',
    'global:for' => 'Pour',
    'global:from' => 'De',
    'global:phone' => 'Téléphone',
    'global:email' => 'Email',
    'global:contacts' => 'Contacts',
    'global:week' => 'Hebdomadaire',
    'global:na' => 'N/D',
    'global:quarterly' => 'Trimestriel',
    'global:every_six_months' => 'Tous les 6 mois',
    'global:statistics' => "Statistiques",
    'global:biyearly' => 'Tous les 2 ans',
    'global:month' => 'Mensuel',
    'global:year' => 'Annuel',
    'global:fax' => 'Fax',
    'global:mobile' => 'Mobile',
    'global:address' => 'Adresse',
    'global:api_key' => 'Clé API',
    'global:website' => 'Site Web',
    'global:action' => 'Action',
    'global:items' => 'Éléments',
    'global:reusableinvoiceitems' => 'Élément de facturation réutilisable',
    'global:reusableinvoiceitems_description' => 'Vous devriez utiliser "Élément de facturation réutilisable" lorsque vous voulez réutiliser le même élément dans d\'autres factures. Pour utiliser ces éléments lorsque vous créez ou utilisez une facture, commencez simplement à taper le nom de l\'item que vous avez sauvegardé et le système vous offrira de compléter automatiquement les détails.',
    'global:create_invoice_estimate' => 'Créez des factures et des estimations pour collecter de l\'argent',
    'global:createinvoice' => 'Créer une facture',
    'global:paid' => 'Payée',
    'global:unpaid' => 'Impayée',
    'global:overdue' => 'En retard',
    'global:time_entries' => 'Saisies de temps',
    'global:invoices' => 'Factures',
    'global:invoice' => 'Facture',
    'global:tasks' => 'Tâches',
    'global:dashboard' => 'Tableau de bord',
    'global:settings' => 'Paramètres',
    'global:plugins' => 'Extensions',
    'global:installed' => 'Installé',
    'global:changepassword' => 'Changer le mot de passe',
    'global:logout' => 'Déconnexion',
    'global:status' => 'Status',
    'global:client' => 'Client',
    'global:user' => 'Utilisateur',
    'global:title' => 'Titre',
    'global:subtitle' => 'Sous-titre',
    'global:to' => 'À (pour utiliser plusieurs adresses, séparez-les par des virgules)',
    'global:subject' => 'Sujet',
    'global:thanks' => 'Merci',
    'global:proposals' => 'Propositions',
    'global:proposal' => 'Proposition',
    'global:reports' => 'Rapports',
    'global:item' => 'Élément',
    'global:report' => 'Rapport',
    'global:saveandinsert' => 'Sauvegarder et insérer',
    'global:details' => 'Détails',
    'global:license_key' => 'Clé de license',
    'global:version' => 'Version :1',
    'global:content' => 'Contenu',
    'global:add' => 'Ajouter',
    'global:edit' => 'Modifier',
    'global:resend' => 'Renvoyer',
    'global:sent' => 'Envoyé',
    'global:not_sent' => 'Non envoyé',
    'global:view' => 'Voir',
    'global:delete' => 'Supprimer',
    'global:remove' => 'Retirer',
    'global:sort' => 'Ordre',
    'global:deleteitem' => 'Supprimer l\'élément',
    'global:dragtoreorder' => 'Glissez pour réordonner',
    'global:start' => 'Démarrer',
    'global:stop' => 'Arrêter',
    'global:start_timer' => 'Démarrer le chronomètre',
    'estimates:create' => "Create Estimate",
    'global:stop_timer' => 'Arrêter le chronomètre',
    'global:created' => 'Créé',
    'global:updated' => 'Mis à jour',
    'global:update' => 'Mettre à jour',
    'global:downloadpdf' => 'Télécharger le PDF',
    'global:yesdelete' => 'Oui, supprimer!',
    'global:confirm_emphisised' => 'Il n\'y a aucun retour en arrière possible!',
    'global:color' => 'Couleur',
    'global:save' => 'Enregistrer',
    'global:unknown' => 'Inconnu',
    'global:upload_ini_size' => 'Le fichier téléversé dépasse la limite de poids imposée par votre installation de PHP.',
    'global:upload_error' => 'Un problème est survenu lors du téléversement du fichier. Veuillez réessayer.',
    'global:recurring' => 'Récurrent',
    'global:unsent' => 'Non envoyé',
    'global:converttoproject' => 'Convertir en projet',
    'global:converttoinvoice' => 'Convertir en facture',
    'global:viewpdf' => 'Voir le PDF',
    'global:duplicate' => 'Dupliquer',
    'global:urltosend' => 'Voici l\'URL à envoyer : ',
    'global:copytoclipboard' => 'Copier dans le presse-papier',
    'global:you_need_pancake_cron_job' => 'Pour utiliser les factures récurrentes, vous devez exécuter la tâche cron de Pancake.',
    'global:if_you_dont_know_how_to_set_it_up' => 'Si vous ne savez pas comment la configurer, <a href="http://help.pancakeapp.com/customer/portal/articles/605703">cliquez ici</a>.',
    'global:quick_links' => 'Liens rapides',
    'global:view_all' => 'Voir tous',
    'global:deleted' => 'Supprimé',
    'global:add_more' => "Ajouter plus",
    'global:upload_files' => "Télécharger des fichiers",
    'global:optional_increment' => '<strong>Optionnel</strong> - sera auto-incrémenté',
    'login:ahoy' => 'Ahoy!',
    'login:readytodothis' => 'Prêt ?',
    'login:sup' => 'Quoi de neuf ?',
    'global:actions' => 'Actions',
    'global:select' => "--- Sélectionner ---",

    /** Début des salutations **/
    'global:greetings' => array('Aloha!', 'Allô,', 'Salut,', 'Quoi de neuf,', 'Whalup !'),
    'global:mark_as_unanswered' => 'Marquer comme sans réponse',
    'global:mark_as_accepted' => 'Marquer comme acceptée',
    'global:mark_as_rejected' => 'Marquer comme rejeté',
    'global:reject_estimate' => 'Refuser le devis',
    'global:accept_estimate' => 'Accepter le devis',
    'global:estimate_rejected' => 'Devis refusé',
    "global:estimate_accepted" => "Devis accepté",
    'global:reject_proposal' => 'Refuser la proposition',
    'global:accept_proposal' => 'Accepter la proposition',
    'global:proposal_rejected' => 'Proposition refusé',
    "global:proposal_accepted" => "Proposition accepté",
    "global:client_area" => "Espace Client",
    "global:admin" => "Admin",
    "global:all_settings" => "Tous les paramètres",
    'global:viewable' => 'Visible dans l\'espace client',
    'global:not_viewable' => 'Non visible dans l\'espace client',
    'global:milestones' => "Etapes",
    /** Fin des salutations **/

    /** Début du tableau de bord **/
    'dashboard:collected' => 'Collecté',
    'dashboard:outstanding' => 'Impayé',
    'dashboard:latest_activity' => 'Activité récente',
    'dashboard:these_are_your_upcoming_tasks' => "Ce sont vos tâches à venir, :1.",
    'dashboard:upcoming_tasks' => 'Tâche à venir',
    /** Fin du tableau de bord **/


    /** Début des utilisateurs **/
    // ==============================
    // = LOGIN PAGE COMPLETED - Lee =
    // ==============================
    'login:forgotinstructions' => 'Veuillez entrer votre courriel afin que nous vous envoyions un courriel de réinitialisation du mot de passe.',
    'login:reset' => 'Réinitialiser &rsaquo;',
    'login:reset' => 'Réinitialiser le mot de passe',
    'login:username' => 'Nom d\'utilisateur',
    'login:password' => 'Mot de passe',
    'login:changepassword' => 'Changer le mot de passe',
    'login:email' => 'Courriel',
    'login:login' => 'Connexion',
    'login:logout' => 'Déconnexion',
    'login:remember' => 'Se souvenir de moi',
    'login:forgot' => 'Mot de passe oublié?',
    'login:cancel' => '&lsaquo; Annuler',
    /** Fin des utilisateurs **/

    /** Début des groupes d'utilisateurs **/
    'groups:edit_title' => 'Modifier le groupe %s',
    'groups:add_title' => 'Ajouter un groupe d\'utilisateurs',
    /** Fin des groupes d'utilisateurs **/

    /** Début des clients **/
    'clients:title' => 'Tous les clients',
    'clients:filter' => 'Filtre de client',
    'clients:add' => 'Ajouter un client',
    'clients:removefilter' => 'Retirer le filtre',
    'clients:edit' => 'Modifier le client',
    'clients:noclienttitle' => 'Vous devez ajouter au moins un client!',
    'clients:noclientbody' => 'Pour leur envoyer des factures. Voulez-vous en ajouter un maintenant?',
    'clients:noclienttitlefilter' => 'Aucun client ne correspond à votre filtre.',
    'clients:hasnoinvoicetitle' => 'Cool! Ce client est bien configuré!',
    'clients:hasnoinvoicebody' => 'Créons une facture pour obtenir ce qui nous est dû. Voulez-vous en ajouter une maintenant?',
    'clients:added' => 'Le client a été ajouté!',
    'clients:edited' => 'Le client a été mis à jour!',
    'clients:deleted' => 'Le client a été supprimé!',
    'clients:does_not_exist' => 'Ce client n\'existe pas!',
    'clients:health_check' => 'Bilan de santé',
    'clients:all' => 'Tous',
    'clients:delete_title' => 'Supprimer ce client?!?!',
    'clients:delete_message' => 'Êtes-vous certain de vouloir supprimer ce client?<br />Cette action supprimera également toutes les factures, les projets et les devis de ce client.',
    'clients:clientaction' => '&nbsp;',
    'clients:passphrase' => 'Phrase secrète',
    'clients:bad_passphrase' => 'La phrase secrète est incorrecte.',
    'clients:total_clients' => 'Total de clients',
    'clients:support' => 'Support',
    'clients:support_rates' => 'Tarifs de support',
    'clients:edit_support_rates' => 'Appliquer les tarifs',
    /** Fin des clients **/


    /** Début des registres de contacts **/
    'contact:title' => 'Historique de contacts récents',
    'contact:method' => 'Méthode de contact',
    'contact:contact' => 'Contact',
    'contact:subject' => 'Sujet',
    'contact:content' => 'Contenu',
    'contact:calling_title' => 'Appel du client ":1"',
    // 'contact:view_all'		=>	'View All',
    /** Fin des registres de contacts **/

    /** Début des factures **/
    'invoices:markassent' => 'Marquer comme envoyé',
    'invoices:invoicedate' => 'Date de facturation',
    'invoices:file_name' => "Nom du fichier",
    'invoices:date_created' => "Date de création",
    'invoices:size' => "Taille",
    'invoices:files' => "Fichiers",
    'invoices:sentbutunpaid' => 'Factures envoyées mais impayées',
    'invoices:duplicated' => 'Facture dupliquée #:1. Le nuémro de la nouvelle facture est #:2.',
    'invoices:all' => 'Toutes les factures',
    'invoices:empty' => 'Aucune facture',
    'invoices:overdue' => 'Factures dûes',
    'invoices:tax_collected' => "Taxe perçue",
    'invoices:paid' => 'Factures payées',
    'invoices:recurringinvoices' => 'Factures récurrentes',
    'invoices:unsentinvoices' => 'Factures non envoyées',
    'invoices:unpaid' => 'Factures non payées',
    'invoices:thisinvoicewaspaidon' => 'Cette facture a été payée le :1. Merci!',
    'invoices:senton' => 'Envoyé le :1',
    'invoices:lastsenton' => 'Dernier envoi le :1 à :2',
    'invoices:paidon' => 'Payée le :1',
    'invoices:paidonsingle' => 'Payé le',
    'invoices:thisinvoiceisunpaid' => 'Cette facture n\'a pas encore été payée',
    'invoices:noinvoicetitle' => 'Vous n\'avez aucune facture pour l\'instant',
    'invoices:noinvoicesforthefilteredclient' => "Vous n'avez pas de factures pour :1.",
    'invoices:noinvoicebody' => 'Vous devriez créer une facture pour un client dès maintenant! <br /> Les clients adorent les factures!',
    'invoices:send_now_title' => 'Envoyer la facture maintenant?',
    'invoices:send_now_body' => 'Remplissez le formulaire ci-dessous et nous enverrons cette facture pour vous.',
    'invoices:newinvoice' => 'Créer une facture',
    'invoices:send_now' => 'Envoyer la facture',
    'invoices:timequantity' => 'Qté/Hres',
    'invoices:ratewithcurrency' => 'Tarif (:1)',
    'invoices:taxable' => 'Taxable',
    'invoices:total' => 'Total',
    'invoices:amount' => 'Montant',
    'invoices:due' => 'Montant dû',
    'invoices:subtotal' => 'Sous-total',
    'invoices:totaltax' => 'Taxes',
    'invoices:filestodownload' => 'Fichiers à télécharger',
    'invoices:added' => 'La facture a été ajoutée!',
    'invoices:fileswillbeavailableafterpay' => 'Ces fichiers seront disponibles au téléchargement seulement lorsque la facture sera complètement payée.',
    'invoices:no_payment_gateways_enabled' => 'Aucune passerelle de paiement n\'a été activée ce qui pourrait rendre le paiement difficile... Activez-en une dans les <a href=":1">paramètres</a>',
    'invoices:invoicenumber' => 'Facture #:1',
    'invoices:number' => 'Facture #',
    'invoices:type' => 'Type de facture',
    'invoices:is_recurring' => 'Récurrente?',
    'invoices:is_paid' => 'Payeé?',
    'invoices:is_sent' => 'Envoyée?',
    'invoices:date_entered' => 'Date de création',
    'invoices:delete_title' => 'Supprimer cette facture?',
    'items:select_time_entry' => 'Entrée de temps',
    'invoices:delete_message' => 'Êtes-vous certain de vouloir supprimer cette facture?',
    'invoices:create' => 'Créer une facture',
    'invoices:edit' => 'Modifier la facture',
    'invoices:amountrequired' => 'Le champ du montant est requis',
    'invoices:currencydoesnotexist' => 'Cette devise n\'existe pas',
    'invoices:unique_id' => 'ID unique',
    'invoices:willreoccurin' => 'Cette facture aura lieu à nouveau dans :1.',
    'invoices:willbesentautomatically' => 'Le client sera alerté par courriel à propos de cette facture le :1.',
    'invoices:thisisareoccurrence' => 'Cette facture est une récurrence de la facture :1.',
    'invoices:clientlastnotifiedon' => 'Le client a été alerté par courriel à propos de cette facture le :1.',
    'invoices:simple' => 'Simple',
    'invoices:simple_help' => 'Une facture simple n\'a aucun élément, seulement un total.',
    'invoices:detailed' => 'Détaillée',
    'invoices:detailed_help' => 'Une facture détaillée vous permet d\'avoir plusieurs éléments facturables.',
    'invoices:estimate_help' => 'Une estimation est comme une facture détaillée (avec plusieurs éléments), mais n\'est pas facturable.',
    'invoices:unpaid_totalamount' => 'Impayé / Montant total',
    'invoices:saveinvoice' => 'Enregistrer la facture',
    'invoices:deleted' => 'La facture a été supprimée!',
    'invoices:view' => 'Voir la facture',
    'invoices:is_viewable' => 'Afficher dans l\'espace client?',
    'invoices:no_invoices' => 'Il n\'y a aucune facture',
    'invoices:addedsuccess' => 'Vous avez ajouté une facture pour',
    'invoices:invoice' => 'facture',
    'invoices:addedconf' => 'Vous avez ajouté la facture # <strong>:1</strong>, totalisant <strong>:2</strong> pour :3:4.',
    'invoices:preview' => 'Prévisualiser la facture',
    'invoices:editinvoice' => 'Modifier la facture #:1',
    'invoices:messageupdated' => 'La facture a été mise à jour!',
    'invoices:resend' => 'Renvoyer la facture',
    'invoices:client_viewed' => ':1 a vu la facture #:2 le :3',
    'invoices:client_paid' => ':1 a payé la facture #:2 le :3',
    'invoice:paid_amount' => 'Payé',
    /** Fin des factures **/

    /** Début des devis **/
    'estimates:attachedtoproposal' => 'Attaché à la proposition #:1',
    'estimates:duplicated' => 'Devis dupliquée #:1. Le numéro du nouveau devis est #:2.',
    'estimates:alltitle' => 'Tous les devis',
    'estimates:attachingtoproposal' => 'Attachement du devis à la proposition... Veuillez patienter.',
    'estimates:delete_title' => 'Supprimer ce devis?',
    'estimates:delete_message' => 'Êtes vous certain de vouloir supprimer ce devis?',
    'estimates:createnew' => 'Créer un devis',
    'estimates:generate_estimate' => 'Générer un devis',
    'estimates:converted' => 'Le devis #:1 a été converti en projet.',
    'estimates:converted_to_invoice' => 'Le devis #:1 a été converti en facture.',
    'estimates:noestimatetitle' => 'Vous n\'avez aucun devis.',
    'estimates:noestimatesforthisclient' => 'Vous n\'avez aucun devis pour ce client.',
    'estimates:noestimatesforthefilteredclient' => "Vous n'avez pas de devis pour :1.",
    'estimates:deleted' => 'Le devis a été supprimé!',
    'estimates:noestimatebody' => 'Vous devriez vous y mettre! Voulez-vous créer un devis maintenant?',
    'estimates:estimatenumber' => 'Devis #:1',
    'estimates:view' => 'Voir le devis',
    'estimates:no_estimates' => 'Il n\'y a aucun devis',
    'estimates:addedsuccess' => 'Vous avez ajouté un devis pour',
    'estimates:estimate' => 'devis',
    'estimates:added' => 'Le devis a bien été ajouté.',
    'estimates:addedconf' => 'Vous avez ajouté le devis # <strong>:1</strong>, totalisant <strong>:2</strong> pour :3:4.',
    'estimates:send_now_title' => 'Envoyer le devis maintenant?',
    'estimates:send_now_body' => 'Remplissez le formulaire ci-dessous et nous enverrons ce devis pour vous.',
    'estimates:send_now' => 'Envoyer le devis',
    'estimates:edit' => 'Modifier le devis',
    'estimates:preview' => 'Prévisualiser le devis',
    'estimates:editestimate' => 'Modifier le devis #:1',
    'estimates:messageupdated' => 'Le devis a été mise à jour!',
    'estimates:client_viewed' => ':1 a vu <a href=":2">le devis #:3</a> le :4',
    'estimates:client_accepted' => ':1 a accepté <a href=":2">le devis #:3</a> le :4',
    'estimates:client_rejected' => ':1 a refusé <a href=":2">le devis #:3</a> le :4',
    'estimates:resend' => 'Renvoyer le devis',
    'estimates:estimatedate' => 'Date du devis',
    /** Fin des devis **/

    /** Début des projets **/
    'projects:status_id' => 'Status de la tâche',
    'projects:projected' => 'Prévu',
    'projects:projected_hours' => 'Heures prévues',
    'projects:navigationitem' => 'Projets',
    'projects:hours_worked' => 'Nombres d\'heures travaillées',
    'projects:hours_worked_short' => 'Heures de travail',
    'projects:alltitle' => 'Tous les projets',
    'projects:totalprojects' => 'Total de projets',
    'projects:noprojecttitle' => 'Il n\'y a pas encore de projet!',
    'projects:noprojecttext' => 'Voulez-vous en ajouter un maintenant?',
    'projects:add' => 'Créer un projet',
    'projects:createfromtemplate' => 'Créer à partir d\'un modèle',
    'projects:doesnotexist' => 'Le projet auquel vous tentez d\'accéder n\'existe pas',
    'projects:edit' => 'Modifier le projet',
    'projects:delete' => 'Supprimer le projet',
    'projects:project' => 'Projet',
    'projects:new_project_from_estimate_without_number' => "Nouveau projet basé sur le devis",
    'projects:new_project_from_estimate_with_number' => "Nouveau projet basé sur le devis #:1",
    'projects:due_date' => 'Date d\'échéance',
    'projects:is_completed' => 'Complet',
    'projects:manage_project' => 'Gérer le projet',
    'projects:areyousuredeletetask' => 'Êtes-vous certain de vouloir supprimer cette tâche?',
    'projects:add_time' => 'Saisir du temps',
    'projects:add_hours' => 'Ajouter les heures',
    'projects:generate_invoice' => 'Générer la facture',
    'projects:no_projects' => 'Il n\'y a aucun projet',
    'projects:archive_proj' => 'Archiver le projet',
    'projects:unarchive_proj' => 'Désarchiver le projet',
    'projects:archive' => 'Voir l\'archive',
    'projects:active' => 'Projets actifs',
    'projects:archived' => 'Projets archivés',
    'projects:noarchivedprojecttitle' => 'Vous n\'avez aucun projet archivé',
    'projects:noarchivedprojecttext' => 'Vous pouvez archiver un projet à partir de la page du projet concerné.',
    'projects:allarchivedtitle' => 'Tous les projets archivés',
    'projects:templatize' => 'Sauvegarder comme modèle',
    'projects:milestone_identifier' => "[Etape: :1]",
    /** Fin des projets **/

    /** Début des étapes **/
    'milestones:add' => 'Ajouter une étape',
    'milestones:edit' => 'Modifier une étape',
    'milestones:delete' => 'Supprimer l\'étape',
    'milestones:milestone' => 'Étape',
    'milestones:target_date' => 'Date cible',
    'milestones:assigned_user' => 'Utilisateur assigné',
    'milestones:select_default' => '-- Aucune étape --',
    'milestones:no_milestone' => 'Tâches sans étape',
    'milestones:add_success' => 'L\'étape ":1" a été ajoutée avec succès',
    'milestones:edit_success' => 'L\'étape ":1" a été modifiée avec succès',
    'milestones:add_failed' => 'L\'étape ":1" n\'a pas pu être modifiée',
    'milestones:edit_failed' => 'L\'étape ":1" n\'a pas pu être ajoutée.',
    'milestones:are_you_sure_delete' => 'Êtes-vous certain de vouloir supprimer cette étape?',
    'milestones:delete_success' => 'L\'étape ":1" a été supprimée avec succès!',
    'milestones:does_not_exist' => 'Cette étape n\'existe pas',
    'milestones:select_assignee_default' => 'N\'assigner personne',
    /** Fin des étapes **/

    /** Début des rappels **/
    'reminders:reminders' => 'Rappels',
    'reminders:send' => 'Envoyer les rappels',
    'reminders:success' => 'Ces rappels ont été envoyés!',
    'reminders:remind' => 'Rappeler',
    'reminders:message' => 'Message',
    'reminders:due' => 'Jours',
    'reminders:details' => 'Détails',
    'reminders:log' => 'Historique',
    /** Fin des rappels **/

    /** Début des modèles de courriels **/
    'emailtemplates:email_templates' => 'Modèle de courriel',
    'emailtemplates:create_template' => 'Créer un nouveau modèle',
    'emailtemplates:add' => 'Créer un nouveau modèle de courriel',
    'emailtemplates:edit' => 'Modifier le modèle de courriel',
    'emailtemplates:manage' => 'Gérer les modèles',
    'emailtemplates:name' => 'Nom',
    'emailtemplates:subject' => 'Sujet',
    'emailtemplates:days' => 'Nombre de jours',
    'emailtemplates:type' => 'Type de modèle',
    'emailtemplates:success' => 'Le modèle de courriel a été créé avec succès.',
    'emailtemplates:edited' => 'Le modèle de courriel a été modifié avec succès.',
    'emailtemplates:does_not_exist' => 'Le modèle de courriel n\'existe pas.',
    'emailtemplates:deleted' => 'Le modèle de courriel a été bien été supprimé.',
    'emailtemplates:delete_title' => 'Supprimer le modèle de courriel.',
    'emailtemplates:delete_message' => 'Êtes-vous certain de vouloir supprimer ce modèle de courriel?',
    /** Fin des modèles de courriels **/

    /** Début des rapports **/
    'reports:perclient' => 'par client',
    'reports:datefrom' => 'De',
    'reports:allclients' => 'Tous les clients',
    'reports:dateto' => 'À',
    'reports:byclient' => 'Client',

    'reports:view' => 'Voir le rapport',
    'reports:show_all' => 'Afficher les rapports',

    'reports:paid_and_unpaid' => "Payé et impayé",
    'reports:paid_vs_unpaid_over_time' => "Payé vs. Impayé dans les temps",
    'reports:per_client' => 'par client',
    'reports:total_with_tax' => "Total avec taxes",
    'reports:total_without_tax' => "Total sans taxes",
    'reports:total_collected' => 'Total recueillis',
    'reports:fees_paid' => 'Frais payés',
    'reports:total_amount' => 'Montant total',
    'reports:paid_amount' => "Montant payé",
    'reports:unpaid_amount' => "Montant impayé",
    'reports:client_name' => "Nom du client",
    'reports:filters' => 'Filtres',
    'reports:selection_explanation' => 'Les factures impayées sont présentés en fonction de leur date d\'échéance.
Les factures payées sont présentés en fonction de leur date de paiement.
Factures avec plus d\'une partie de paiement sont indiquées sur la base de la date de paiement de la première partie.
Les factures impayées sans date d\'échéance sont présentés en fonction de la date à laquelle ils ont été créés.',
    'reports:nodata' => 'No :1.',
    /** Fin des rapports **/

    /** Début des devises **/
    'currencies:default' => '[Défaut] :1',
    'currencies:cad' => 'Dollar canadien',
    'currencies:eur' => 'Euro',
    'currencies:usd' => 'Dollar U.S.',
    'currencies:gbp' => 'Livre Sterling',
    'currencies:hkd' => 'Dollar de Hong Kong',
    'currencies:php' => 'Perso Philippin',
    'currencies:zar' => 'Rand (Afrique du Sud)',
    /** Fin des devises **/

    /** Début des propositions **/
    'proposals:duplicated' => 'Proposition dupliquée #:1. Le numéro de la nouvelle proposition est #:2.',
    'proposals:usesectiontemplate' => 'Utiliser ce modèle de section',
    'proposals:showcontents' => 'Voir le contenu',
    'proposals:hidecontents' => 'Cacher le contenu',
    'proposals:deletepremadesection' => 'Supprimer ce modèle de section',
    'proposals:nopremadesections' => 'Vous n\'avez sauvegardé aucun modèle de section',
    'proposals:newproposal' => 'Nouvelle proposition',
    'proposals:estimatexfory' => 'Estimé #:1 - :2',
    'proposals:number' => 'Proposition #',
    'proposals:all' => 'Toutes les propositions',
    'proposals:noproposaltitle' => "Il n'y a aucune proposition!",
    'proposals:noproposalbody' => "Vous devriez créer une proposition. Maintenant. Oui oui!",
    'proposals:client_viewed' => ':1 a vu <a href=":2">la proposition #:3</a> le :4',
    'proposals:client_accepted' => ':1 a accepté <a href=":2">la proposition #:3</a> le :4',
    'proposals:client_rejected' => ':1 a refusé <a href=":2">la proposition #:3</a> le :4',
    'proposals:rejected' => 'Refusé le :1',
    'proposals:accepted' => 'Accepté le :1',
    'proposals:lastviewed' => 'Vu la dernière fois par le client le :1, à :2.',
    'proposals:neverviewed' => 'non vu par le client.',
    'proposals:noanswer' => 'Aucune réponse',
    'proposals:createproposal' => 'Créer une proposition',
    'proposals:editproposal' => 'Modifier la proposition',
    'proposals:createdsuccessfully' => 'Proposition créée avec succès!',
    'proposals:sections' => 'Sections',
    'proposals:section' => 'Section',
    'proposals:createsection' => 'Ajouter une nouvelle section',
    'proposals:createpage' => 'Ajouter une page',
    'proposals:emptysection' => '(aucun titre)',
    'proposals:emptycontents' => '(aucun contenu)',
    'proposals:emptysubtitle' => '(aucun sous-titre)',
    'proposals:for' => 'Proposition pour : ',
    'proposals:pagexofcount' => 'Page :1 de :2',
    'proposals:saving' => 'Enregistrement...',
    'proposals:save' => 'Sauvegarder la proposition',
    'proposals:savepremade' => 'Sauvegarder comme modèle de section',
    'proposals:addestimate' => 'Ajouter un devis',
    'proposals:saved' => 'Sauvegardé',
    'proposals:createandedit' => 'Suivant : Modifier le contenu de la proposition',
    'proposals:delete_message' => 'Êtes-vous certain de vouloir supprimer cette proposition?',
    'proposals:createpremadesection' => 'Ajouter à partir du modèle de section',
    'proposals:selected_attachments' => 'Sélectionner le devis',
    'proposals:attach_selected_estimate' => 'Joindre le devis sélectionné',
    'proposals:proposal' => 'Proposition',
    'proposals:status' => 'Status',
    'proposals:view' => 'Voir la proposition',
    'proposals:estimate' => 'Devis',
    'proposals:na' => 'ND',
    'proposals:no_proposals' => 'Il n\'y a aucune proposition',
    'proposals:proposal_title' => 'Titre du devis',
    'proposals:kitchennotice' => 'Note : Les propositions apparaîtront dans le :1 une fois que le client aura visionné le lien de la proposition. Autrement dit, vous pouvez modifier tout ce que vous voulez et le client ne verra ces modifications que lorsque vous le voudrez.',
    'proposal:outline' => 'Plan de proposition',
    /** Fin des propositions **/

    /** Début des tâches **/
    'tasks:task' => 'Tâche',
    'tasks:edit_succeeded' => 'Tâche modifiée avec succès',
    'tasks:hours' => 'Heures',
    'tasks:due_date' => 'Date d\'échéance',
    'tasks:is_completed' => 'Complété?',
    'tasks:timer' => 'Chronomètre',
    'tasks:rate' => 'Tarif',
    'tasks:default_rate' => 'Tarif par défaut',
    'tasks:entries' => 'Saisies de temps',
    'tasks:view_entries' => 'Voir les saisies',
    'tasks:edit_entry' => 'Modifier la saisie',
    'tasks:create' => "Ajouter une tâche",
    'tasks:create_sub' => "Ajouter une sous-tâche",
    'tasks:task_parent' => "Tâche parente",
    'tasks:edit' => "Modifier la tâche",
    'tasks:create_succeeded' => "La tâche a été créée",
    'tasks:no_task_title' => 'Il n\'y a pas encore de tâche',
    'tasks:no_task' => "Pas de tâche",
    'tasks:no_task_message' => 'Vous devriez en créer une tâche',
    'tasks:is_viewable' => 'Visible dans l\'espace client',
    'tasks:no_milestones' => 'Tâches sans étape.',
    'tasks:not_related_to_a_task' => "-- Non associé à une tâche --",
    'tasks:select_parent_default' => '-- Aucune tâche parente --',
    'tasks:timers_running' => 'Chronomètres',
    'tasks:task_completed_by' => ':1 a complété la tâche :2 à :3',
    'tasks:discussion' => 'Discussion : ',
    'tasks:billed_hours' => "Heures facturées",
    'tasks:unbilled_hours' => "Heures non-facturées",
    /** Fin des tâches **/

    /** Début des utilisateurs **/
    'users:create_user' => 'Créer un utilisateur',
    'users:confirm_delete_emphasised' => "Cette action est définitive!",
    /** Fin des utilisateurs **/

    /** Début des items **/
    'items:name'						=> 'Nom de l\'élément',
    'items:description'					=> 'Description de l\'élément',
    'items:qty_hrs'						=> 'Qté / Hres',
    'items:quantity'					=> 'Quantité',
    'items:rate'						=> 'Tarif',
    'items:tax_rate'					=> 'Taux de taxes',
    'items:cost'						=> 'Coût',
    'items:line_items'					=> 'Élément',
    'items:add'							=> 'Ajouter un élément',
    'items:edit'						=> 'Modifier l\'élément',
    'items:noitemtitle'					=>	'Vous n\'avez pas encore d\'élément!',
    'items:noitembody'					=>	'Vous devriez ajouter des éléments maintennat, ça rend la création de facture vraiment facile!',
    'items:delete_title'				=>	'Supprimer cet élément?',
    'items:delete_message'				=>	'Êtes-vous certain de vouloir supprimer l\'élément ":1"?',
    'items:type'						=> 'Type',
    'items:select_standard'				=> 'Standard',
    'items:select_expense'				=> 'Dépense',
    'items:add_expense_to_project'		=> 'Ajouter une dépense',
    'items:expenses'					=> 'Dépenses',
    /** Fin des items **/

    /** Début des dépenses **/
    'expenses:expenses'					=>	'Dépenses',
    'expenses:add'						=>	'Ajouter une dépense',
    'expenses:edit_expense'				=>	'Modifier la dépense',
    'expenses:delete'					=>	'Supprimer la dépense',
    'expenses:deleted'					=>	'Dépense supprimée',
    'expenses:all'						=>	'Toutes les dépenses',
    'expenses:amount'					=>	'Montant',
    'expenses:supplier'					=>	'Fournisseur',
    'expenses:suppliers'				=>	'Fournisseurs',
    'expenses:category'					=>	'Catégorie',
    'expenses:categories'				=>	'Catégories',
    'expenses:add_supplier'				=>	'Ajouter un fournisseur',
    'expenses:edit_supplier'			=>	'Modifier le fournisseur',
    'expenses:add_category'				=>	'Ajouter une catégorie',
    'expenses:edit_category'			=>	'Modifier la catégorie',
    'expenses:parent_category'			=>	'Catégorie parente',
    'expenses:filter'					=>	'Filtrer les dépenses',
    'expenses:start_date'				=>	'Date de début',
    'expenses:end_date'					=>	'Date de fin',
    /** Fin des dépenses **/

    /** Début des transactions **/
    'transactions:paymentcancelled'				=> 'Paiement annulé',
    'transactions:extrapaymentcancelled'		=> 'Votre paiement a été annulé',
    'transactions:paymentreceived'				=> 'Paiement reçu',
    'transactions:fee_applied'					=> 'Comme :1 impose ses propres frais de transaction, nous avons ajouté :2% au montant.',
    'transactions:orderbeingprocessed'			=> 'Veuillez patienter, votre commande est en cours de traitement et vous serez redigiré vers le site :1 sous peu.',
    'transactions:ifyouarenotredirected'		=> 'Si vous n\'êtes pas redirigé automatiquement vers :1 dans 5 secondes...',
    'transactions:thankyouforyourpayment'		=> 'Merci pour votre paiement. Vous devriez recevoir le reçu par courriel sous peu.',
    'transactions:ifyouhavefilesyouwillgetanemail'		=> 'Si vous attendez la livraison de fichiers, vous recevrez un courriel contenant un lien pour les télécharger sous peu.',
    'transactions:ifyoudonotreceiveemail'		=> 'Si vous ne recevez pas de courriel d\'ici une heure, veuillez contacter :1',
    /** Fin des transactions **/

    /** Début feuilles de temps **/
    'timesheet:taskname'			=> 'Nom de la tâche',
    'timesheet:starttime'			=> 'Départ',
    'timesheet:endtime'				=> 'Fin',
    'timesheet:timeframe'			=> 'Délais',
    'timesheet:duration'			=> 'Durée',
    'timesheet:date'				=> 'Date',
    'timesheet:forproject'			=> 'Feuille de temps pour le projet ":1"',
    'timesheet:timesheet'			=> 'Feuille de temps',
    'timesheet:for'					=> 'Feuille de temps pour : ',
    'timesheet:totalbillable'		=> 'Total d\'heures facturables',
    'timesheet:view_pdf'			=> 'Voir la feuille de temps',
    'timesheet:user'			    => 'Utilisateur',
    'timesheet:entries'			    => 'Saisies',
    'timesheet:no_entries'                  => "Il n'y a aucune saisie de temps",
    /** Fin des feuilles de temps **/


    /** Début billets de support **/

    'tickets:all_tickets'			=>	'Tickets du support',
    'tickets:support_tickets' => "Tickets du support",
    'tickets:pending'				=>	'En attente',
    'tickets:open'					=>	'Ouvert',
    'tickets:resolved'				=>	'Résolu',
    'tickets:closed'				=>	'Fermé',
    'tickets:respond'				=>	'Répondre au ticket',
    'tickets:ticket_options'		=>	'Options de ticket',
    'tickets:attachment'			=>	'Pièces jointes',
    'tickets:updated_status'		=>	':1 a mis à jour le status du ticket pour :2',
    'tickets:add_a_new_ticket' => "Ajouter un nouveau ticket",
    'tickets:create_a_new_ticket' => 'Créer un nouveau ticket',
    'tickets:add_ticket' => 'Ajouter un ticket',
    'tickets:assign_to_user' => 'Assigner à l\'utilisateur',
    'tickets:select_client' => 'Sélectionnez le client',
    'tickets:ticket_subject' => 'Objet du ticket',
    'tickets:ticket_message' => 'Message du ticket',
    'tickets:ticket_priority' => 'Priorité du ticket',
    'tickets:ticket_status' => 'Status du ticket',
    'tickets:no_priority' => '-- Aucune priorité --',
    'tickets:no_status' => '-- Aucun statut --',
    'tickets:no_posts' => "Aucun message.",

    /** Fin des billets de support **/

    /** Frontend **/
    'frontend:hithere'						=> 'Bonjour !',
    'frontend:followthemaillinkdude'		=> 'Pour voir votre facture, vous devez cliquer sur le lien entier dans le courriel que vous avez reçu. Le lien ressemble à ceci : :1.',
    'frontend:contactadminforassistance'	=> 'Pour toute assistance, veuillez contacter :1 @ :2',
    /** Fin Frontend **/

    /** Settings **/

    'settings:task_statuses'						=> "Status des tâches",
    'settings:ticket_statuses'						=> "Status des tickets",
    'settings:ticket_priorities'					=> "Priorités des tickets",
    'settings:background_color'						=> "Couleur de fond",
    'settings:text_color'							=> "Couleur du texte",
    'settings:text_shadow'							=> "Ombre du texte",
    'settings:box_shadow'							=> "Ombre portée",
    'settings:default_rate'							=> "Tarif par défaut",
    'settings:allowed_extensions'					=> 'Permettre le téléversement d\'extension',
    'settings:comma_separated'						=> 'séparé par des virgules',
    'settings:pdf_page_size'						=> 'Dimensions de la page des PDF générés',
    'settings:default_invoice_notes'				=> 'Notes par défaut de la facture',
    'settings:default_invoice_title'				=> 'Titre par défaut de la facture',
    'settings:default_invoice_due_date'				=> 'Date d\'échéance par défaut',
    'settings:autosave_proposals'					=> 'Sauvegarder automatiquement le devis',
    'settings:default_invoice_due_date_explain'		=> 'jours après la création de la facture. Si vous ne voulez pas de date par défaut, laissez ce champ vide.',
    'settings:testemailsettings'					=> 'Paramètres de courriels tests',
    'settings:kitchen_route'						=> 'Préfixe de l\'accès client',
    'settings:kitchen_route_explain'				=> "(Prévisualiser: :1)",
    'settings:include_remittance_slip'				=> 'Bordereaux de paiement',
    'settings:include_remittance_slip_explain'		=> "Si ce paramètre est sélectionné, le PDF de la facture incluera un bordereau de paiement.",
    'settings:items_per_page'						=> 'Éléments par page',
    'settings:items_per_page_explain'				=> 'Nombre d\'éléments (factures/etimés/devis/projets/tâches) à afficher par page.',
    'settings:send_x_days_before'					=> '"Envoyer x jours d\'avance" par défaut',
    'settings:send_x_days_before_explain'			=> "Nombre de jours d'avance par défaut qu'une facture récurrente est envoyée au client.",
    'settings:file_to_import'						=> 'Fichier à importer',
    'settings:export_types'							=> 'Pancake exporte le tout en format JSON.',
    'settings:file_should_be_csv'					=> 'Pancake traitera automatiquement votre fichier et importera le tout. Si Pancake est incapable de traiter votre fichier, il vous le laissera savoir et il vous donnera l\'option de nous envoyer quelques informations pour rendre Pancake fonctionnel avec votre fichier.',
    'settings:importnow'							=> 'Importer maintenant!',
    'settings:whatimporting'						=> 'Que voulez-vous importer?',
    'settings:whatexporting'						=> 'Que voulez-vous exporter?',
    'settings:nouploadedimportfile'					=> 'Vous n\'avez pas téléversé un fichier à importer',
    'settings:import'								=> 'Importer (bêta)',
    'settings:importedclients'						=> ':1 clients importés avec succès.',
    'settings:importedprojects'                                         => "Importé :1 projets avec succès.",
    'settings:importedusers'                                            => "Importé :1 utilisteurs avec succès.",
    'settings:importedinvoices'						=> 'Importé :1 factures avec succès.',
    'settings:importedtasks'						=> 'Importé :1 tâches avec succès.',
    'settings:importedestimates' => 'Importé :1 estimés avec succès.',
    'settings:importedtime_entries'					=> 'Importé :1 saisies de temps avec succès.',
    'settings:xwereduplicates'						=> ':1 étaient des duplicatas et ont été ignorés.',
    'settings:import_desc'							=> 'Importer des données dans Pancake.',
    'settings:export'								=> 'Exporter',
    'settings:exportnow'							=> 'Exporter maintenant!',
    'settings:importexport'							=> 'Importer / Exporter',
    'settings:removelogo'							=> 'Retirer le logo',
    'settings:wrong_license_key'					=> 'La clé de license que vous avez entré n\'est pas valide',
    'settings:noopenssl'							=> 'Votre serveur PHP n\'a pas de configuration OpenSSL active ce qui veut dire que vous ne pouvez pas utiliser Gmail ou d\'autres applications Google pour envoyer des courriels',
    'settings:logoremoved'							=> 'Logo retiré avec succès!',
    'settings:save'									=> 'Sauvegarder',
    'settings:logodimensions'						=> 'Le logo devrait être d\'au moins 240 pixels de large et 106 pixels de haut',
    'settings:logoformatsallowed'					=> 'Seulement les fichiers de type BMP, PNG, JPG (JPEG) et GIF sont autorisés',
    'settings:ftp_user'								=> 'Utilisateur FTP',
    'settings:ftp_pass'								=> 'Mot de passe FTP',
    'settings:ftp_path'								=> 'Chemin FTP',
    'settings:ftp_port'								=> 'Port FTP',
    'settings:ftp_pasv'								=> 'Mode passif?',
    'settings:nophpupdates'							=> "À cause de la façon dont votre serveur est configuré, vous devez entrer vos informations FTP pour que Pancake puisse se mettre à jour. Cet informations ne sont utilisées qu'à l'interne de Pancake et ne seront jamais transmises à personne.",
    'settings:ftp_host'								=> 'Hôte FTP',
    'settings:uptodate'								=> 'Pancake est bien à jour (:1)',
    'settings:newversionavailable'					=> 'Une nouvelle version de Pancake est disponible (:1)!',
    'settings:updatenow'							=> 'Mettre à jour maintenant!',
    'settings:checkforupdates' => "Vérifier les mises à jour",
    'settings:youneedtoconfigurefirst'				=> 'Votre Pancake n\'est pas configuré pour se mettre à jour. Veuillez entrer vos informations de connexion FTP ci-dessous et cliquez sur "Sauvegarder les configurations".<br>Pancake vous laissera ensuite le mettre à jour',
    'settings:general'								=> 'Général',
    'settings:emails' => 'Emails',
    'settings:email_templates'						=> 'Courriels',
    'settings:taxes'								=> 'Taxes',
    'settings:currencies'							=> 'Devises',
    'settings:branding'								=> 'Branding',
    'settings:payment_methods'						=> 'Paiements',
    'settings:feeds'								=> 'Flux',
    'settings:api_keys'								=> 'Clés d\'API',

    'settings:time_entry_times' => "Entrés de temps",
    "settings:include_dates_and_times_in_line_items" => 'Inclure les dates et les heures dans l\'item Entrés de temps.',
    "settings:when_generating_invoice" => "Lors de la génération des factures , utiliser une ligne par",
    "settings:use_utf8_font" => "Utilisez des polices UTF-8 dans les fichiers PDF",
    "settings:use_utf8_font_explanation" => "Utilisez cette option si les caractères sont brisés dans vos fichiers PDF .",
    "settings:pdf_attachments" => "Pièces jointes PDF",
    "settings:pdf_attachments_explanation" => "Si elle est cochée , Pancake va fixer le PDF correspondant à la facture , devis ou proposition par emails.",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",

    'settings:site_name'			=> 'Nom du site',
    'settings:language'				=> 'Langue',
    'settings:timezone'				=> 'Fuseau horaire',
    'settings:notify_email'			=> 'Courriel de notification',
    'settings:currency'				=> 'Devise',
    'settings:theme'				=> 'Thème frontend',
    'settings:admin_theme'			=> 'Thème de l\'admin',
    'settings:admin_name'			=> 'Nom de l\'admin',
    'settings:date_format'			=> 'Format de date',
    'settings:time_format' => "Format de l'heure",
    'settings:task_time_interval'	=> 'Arrondir les saisies de temps (laissez vide pour ne pas arrondir)',
    'settings:task_time_interval_description' => '(ex.: 00:30 ou 0.5 - toutes les saisies de temps seront arrondies à la demi-heure près lors de la génération de facture.)',
    'settings:mailing_address'		=> 'Adresse postale',

    'settings:default_subject'			=> 'Sujet par défaut',
    'settings:default_contents'			=> 'Message par défaut',
    'settings:new_estimate'				=> 'Nouvel estimé',
    'settings:new_invoice'				=> 'Nouvelle facture',
    'settings:new_proposal'				=> 'Nouveau devis',
    'settings:paid_notification'		=> 'Notification de paiement',
    'settings:payment_receipt'			=> 'Reçu de paiement',
    'settings:new_ticket'				=> 'Nouveau billet',
    'settings:ticket_invoice'			=> "Nouvelle facture de billet",
    'settings:ticket_updated'			=> 'Billet mis à jour',
    'settings:ticket_status_updated'	=> 'Status du billet mis à jour',

    'settings:logo'					=> 'Votre logo',
    'settings:frontend_css'			=> 'CSS personnalisé du frontend',
    'settings:backend_css'			=> 'CSS personnalisé de l\'admin',

    'settings:rss_password'			=> 'Mot de passe du fil RSS',
    'settings:default_feeds'		=> 'Flux par défaut',
    'settings:cron_job_feed'		=> 'Tâche cron',
    'settings:feed_generator'		=> 'Générateur de flux',
    'settings:your_link'			=> 'Votre lien',
    'settings:bcc'					=> 'BCC',
    'settings:automaticallybccclientemail'		=> 'Envoyer une copie de chaque courriel envoyé aux clients à l\'adresse courriel de notification (définie ci-haut)',
    'settings:api_note'				=> 'Nom / note',
    'settings:api_key'				=> 'Clé API',

    'settings:tax_name'				=> 'Nom de taxe',
    'settings:tax_value'			=> 'Valeur',
    'settings:tax_reg'				=> 'Numéro d\'enregistrement aux taxes',
    'settings:add_tax'				=> 'Ajouter une autre taxe',

    'settings:currency_name'		=> 'Nom de la device',
    'settings:currency_code'		=> 'Code de la devise',
    'settings:exchange_rate'		=> 'Taux de change',
    'settings:add_currency'			=> 'Ajouter une autre devise',
    /** Fin Settings **/

    'update:ifyourenotsurecontactus'		=> "Si vous n'êtes pas certain de ce que vous faites, veuillez <a href='http://pancakeapp.com/forums/newtopic/2/'>commencer un nouveau ticket de support dans le forum</a>.",
    'update:youmodified'					=> 'Vous avez modifié',
    'update:youdeleted'						=> 'Vous avez supprimé',
    'update:loadingpleasewait'				=> 'Chargement, veuillez patienter.',
    'update:errordownloading'				=> 'Une mise à jour de Pancake est disponible, mais des problèmes sont survenus lors du téléchargement.',
    'update:herearestepstofix'				=> 'Voici quelques étapes que vous pouvez essayer afin de corriger le problème : ',
    'update:makesureuploadsiswritable'		=> 'Assurez-vous que votre dossier de téléversement est inscriptible (CHMOD 0777).',
    'update:deletepancakesystemupdate'		=> 'Supprimez le dossier pancake-update-system (à l\'intérieur du dossier de uploads) et tout ce qu\'il contient.',
    'update:loadpancakeagain'				=> "Ouvrez Pancake à nouveau. Si l'erreur persiste, changez le propriétaire du dossier Pancake (CHOWN) pour qu'il corresponde à l'utilisateur de votre serveur.",
    'update:whatschanged'					=> "Quoi de neuf dans :1",
    'update:ftp_conn'						=> 'Pancake n\'a pas pu se connecter à l\'hôte FTP',
    'update:ftp_login'						=> 'Pancake n\'a pas pu se connecter via FTP (mot de passe ou utilisateur FTP erronné)',
    'update:ftp_chdir'						=> 'Pancake n\'a pas pu configurer le chemin FTP (le chemin vers ce dossier n\'existe probablement pas)',
    'update:ftp_no_uploads'					=> 'Pancake n\'a pas pu obtenir les permissions nécessaires pour téléverser des fichiers par FTP.',
    'update:ftp_indexwrong'					=> 'Le chemin FTP que vous avez entré est incorrect. Le chemin devrait être celui du dossier de Pancake.',
    'update:ftp_indexnotfound'				=> 'Le chemin FTP que vous avez entré est incorrect. Le chemin devrait être celui du dossier de Pancake.',
    'update:update_conflict'				=> 'Vous avez modifié certains fichiers depuis la dernière mise à jour. Dans le but de sauvegarder vos modifications, voici une liste des fichiers que vous avez modifiés qui entrent en conflit avec la mise à jour la plus récente.',
    'update:update_no_perms'				=> 'Pancake n\'a pas les permissions suffisantes pour se mettre à jour et il n\'a pas accès à un compte FTP duquel il peut se mettre à jour. La mise à jour ne peut pas continuer',
    'update:review_files'					=> 'Veuillez réviser ces fichiers et en faire une sauvegarde avant de procéder. Lorsque la mise à jour sera terminée, vous devrez réintégrer vos modifications dans ceux-ci. Veuillez ne pas simplement remplacer le nouveau fichier par l\'ancien puisque certaines fonctionnalités pourraient être écrasées.',
    'update:internetissues'					=> "Pancake est incapable de se connecter à Internet.",
    'update:pancakeneedsinternet'			=> 'Pour que Pancake fonctionne correctement, votre serveur doit lui permettre de requérir certaines informations provenant d\'Internet (port 80)',
    'update:maybefirewall'					=> "Il semblerait que votre serveur empêche Pancake d'accéder à Internet. Il pourrait s'agir d'un problème de pare-feu de la part de votre serveur. Veuillez contacter votre hébergeur et demandez-lui de permettre PHP d'accéder à :1.",
    'update:nointernetaccess'				=> 'Aucun accès Internet',
    'update:pancakeupdated'					=> 'Pancake a été mis à jour de :1 à :2',

    /** Début paiements partiaux **/
    'partial:partialpayments'			=> 'Plan de paiement',
    'partial:totalamounttobepaid'		=> "Montant total devant être payé par le client",
    'partial:amountlefttobeadded'		=> "Montant restant devant être ajouté au plan de paiement",
    'partial:amounttoobig'				=> "Montant devant être retiré du plan de paiement.",
    'partial:noamountneeded'			=> "Votre paiement est complété.",
    'partial:amount'        			=> 'Montant',
    'partial:add_payment'				=> 'Ajouter un paiement',
    'partial:dueon'         			=> 'Dû le',
    'partial:addanother'     			=> 'Ajouter une autre étape à ce paiement',
    'partial:disabledforrecurring'		=> 'Les factures récurrentes sont limitées à une seule étape de paiement',
    'partial:paymentdetails'			=> 'Détails du paiement',
    'partial:wrongtotal'				=> 'La somme de toutes les étapes du plan de paiement ne correspond pas au montant total que vous êtes en train de facturer.',
    'partial:problemsaving'				=> 'Une erreur s\'est produite lors de la sauvegarde du plan de paiement. Veuillez réessayer.',
    'partial:wrongtotalbutsaved'		=> 'La somme de toutes les étapes du plan de paiement ne corresspond pas au montant total que vous êtes en train de facturer.<br>Les changements à votre facture ont été sauvegardés, mais vous devez corriger votre plan de paiement.',
    'partial:problemsavingbutsaved'		=> 'Un problème est survenu lors de la sauvegarde de votre plan de paiement. Veuillez réessayer.<br>Les changements à votre facture ont été sauvegardés tandis que les changements au plan de paiement ne l\'ont pas été.',
    'partial:savepaymentdetails'		=> 'Sauvegarder les détails de paiement',
    'partial:partpaidthanks'			=> "Cette partie de votre facture a été payée. Merci.",
    'partial:proceedtopayment'			=> 'Procédez au paiement',
    'partial:topaynowgoto'				=> 'Pour payer maintenant, veuillez vous rendre au :1',
    'partial:pay_part_x_now' => "Payez la partie #:1 de votre facture maintenant",
    'partial:dueondate'					=> 'dû le :1',
    'partial:paymentmethod'				=> 'Méthode de paiement',
    'partial:paymentdate'				=> 'Date du paiement',
    'partial:paymentstatus'				=> 'Status du paiement',
    'partial:transactionid'				=> 'ID de transaction',
    'partial:markaspaid'				=> 'Marquer comme payé',
    'partial:transactionfee'			=> 'Frais de transaction',
    /** Fin paiements partiaux **/

    /** Début méthodes de paiement **/
    'paypal:clickhere'					=> 'Cliquez ici pour procéder',
    'authorize:transaction_key'			=> 'Clé de transaction',
    'paypal:email'   					=> 'Courriel PayPal',
    'paypal:fee'    					=> 'Frais PayPal (%)',
    'paypalpro:paypalpro'				=> 'Paiement par PayPal Pro (BETA)',
    'paypalpro:viacreditcard'			=> 'Payer par carte de crédit',
    'cash:cash'							=> 'Argent',
    'check:check'						=> 'Chèque',
    'moneyorder:moneyorder'				=> 'Mandat-poste',
    'creditcard:creditcard'				=> 'Carte de crédit',
    'banktransfer:banktransfer'			=> 'Transfert bancaire',
    'gateways:errorupdating'			=> 'Une erreur s\'est produite lors de la mise à jour de vos paramètres de paiement. Veuillez contacter le support.',
    'gateways:paymentmethods'			=> 'Méthodes de paiement',
    'gateways:selectpaymentmethod'		=> 'Sélectionnez une méthode de paiement',
    'gateways:nogatewayused'			=> 'Aucune méthode de paiement n\'a été utilisée. Une partie reste impayée.',
    'gateways:completed'				=> 'Complété',
    'gateways:refunded'					=> 'Remboursé',
    'gateways:unpaid'					=> 'Impayé',
    'gateways:paymentrejected'			=> ':1 Paiement rejeté',
    'gateways:rejectedemail'			=> 'Pancake a été notifié à propos d\'un :1 paiement qu\'un de vos clients (:2) a  fait, mais Pancake l\'a rejeté.',
    'gateways:pending'					=> 'En cours',
    'gateways:returntowebsite'			=> 'Retourner à :1',
    'gateways:cc_type'					=> 'Type de carte de crédit',
    'gateways:cc_number'				=> 'Numéro de carte de crédit',
    'gateways:cc_exp'					=> 'Date d\'expiration',
    'gateways:cc_cardholder'			=> 'Nom du détenteur de la carte',
    'gateways:cc_code'					=> 'Code de sécurité',
    'gateways:payment_details'			=> 'Détails de paiement',
    'gateways:api_signature'			=> 'Signature de l\'API',
    'gateways:api_password'				=> 'Mot de passe de l\'API',
    'gateways:api_username'				=> 'Nom d\'utilisateur de l\'API',
    /** Fin méthodes de paiement **/

    /** Kitchen Area **/
    'kitchen:edit_comment'				=> 'Modifier le commentaire',
    'kitchen:add_a_comment' => "Ajouter un commentaire",
    'kitchen:kitchen_name' 				=>  'Espace client',
    'kitchen:pleaselogin' 				=>  'Veuillez entrer votre mot de passe pour accéder à votre compte',
    'kitchen:nocomments'    			=>  'Aucun commentaire',
    'kitchen:comment'   				=>  'Commentaire',
    'kitchen:comments'  				=>  'Commentaires',
    'kitchen:comments_x' => 'Commentaires (:1)',
    'kitchen:file'  					=>  'Fichier',
    'kitchen:submitcomment'				=>  'Ajouter un commentaire',
    'kitchen:attachment'    			=>  'Pièce jointe',
    'kitchen:saidon'    				=>  'a dit le :1, à :2',
    'kitchen:subjectinvoice'			=> 'Nouveau commentaire pour la facture #',
    'kitchen:subjectestimate'			=> 'Nouveau commentaire pour l\'estimé #',
    'kitchen:subjectproject'			=> 'Nouveau commentaire pour le projet : ',
    'kitchen:subjecttask'				=> 'Nouveau commentaire pour la tâche : ',
    'kitchen:subjectproposal'			=> 'Nouveau commentaire pour le devis : ',
    'kitchen:backtodashboard'   		=>  'Retourner au panneau de contrôle',
    'kitchen:client_welcome'    		=>  'Espace client pour : ',
    'kitchen:urltosend'					=>  'URL de l\'espace client',
    'kitchen:nopassphrase'  			=>  'Présentement, le mot de passe client n\'est pas configuré, ce qui veut dire qu\'accéder à cet URL est tout ce qu\'il faut faire pour voir l\'accès client. Si vous voulez sécuriser l\'accès et ajouter un mot de passe, éditez ce client pour ce faire.',
    'kitchen:passphraseset'				=>  'Ce client a un mot de passe déjà configuré',
    'kitchen:passphrase'    			=>  'Mot de passe',
    'kitchen:description'   			=>  'Ceci est l\'URL à envoyer à votre client pour lui permettre d\'accéder à l\'espace client où il peut voir ses éléments (projets, facutres) que vous avez rendus visibles de son côté.',
    'kitchen:people_in_discussion'		=>  'Personnes dans la conversation',

    'kitchen:latest_invoice' => 'Dernière facture',
    'kitchen:unpaid_balance' => 'Solde impayé: :1',
    'kitchen:total_paid_to_date' => 'Total payé à ce jour: :1',

    /** Fin Kitchen Area **/

    'store:store' => 'Magasin',
    'store:buy' => "Acheter ($:1)",
    'store:update' => "Mettre à jour",
    'store:install' => "Installer",
    'store:settings' => "Paramètres",
    'store:already_bought' => "Vous avez déjà acheté cet article!",
    'store:installed_successfully' => "Vous avez installé le :1 :2 avec succès.",
    'store:plugin' => "Plugin",
    'store:payment_gateway' => "Passerelle de paiement",
    'store:frontend_theme' => "Thème accès client",
    'store:backend_theme' => "Thème d'administration",
    'store:unknown' => "Inconnu",
    'store:updatestoreitems' => "Mise à jour des articles du magasin",
    'store:download_free' => "Télécharger gratuitement",
    'store:error1000' => "Votre jeton d'autorisation n'est plus valide. Vous devrez entrer vos informations de paiement dans pancakeapp.com une fois de plus.",
    'store:error1001' => "Vous avez déjà acheté cet article de magasin!",
    'store:error1002' => "Un problème est survenu lors de la tentative de débiter votre carte de crédit. Réessayez plus tard.",
    'store:error1003' => "Vous avez fait une demande non valide.",

    'email_templates:new_invoice' => 'Nouvelle facture',
    'email_templates:new_estimate' => 'Nouveau devis',
    'email_templates:new_proposal' => 'Nouvelle proposition',
    'email_templates:invoice_payment_notification_for_admin' => 'Avis de paiement (envoyé à l\'admin)',
    'email_templates:invoice_payment_notification_for_client' => 'Notification de réception de paiement (envoyé au client)',
    'email_templates:new_ticket' => 'Nouveau Ticket',
    'email_templates:new_ticket_invoice' => 'Nouveau ticket facture',
    'email_templates:ticket_updated' => 'Notification de mise à jour d\'un billet',
    'email_templates:ticket_status_updated' => 'Notification de mise à jour du status d\'un billet',
    'email_templates:assigned_to_task' => "Notification d'affectation des tâches",
    'email_templates:assigned_to_milestone' => "Notification d'affectation d'une étape",
    'email_templates:new_comment' => "Notification de nouveau commentaire",
    'global:timer_app' => "Minuteur Pancake",

    # v4.0.5
    'invoices:lastreoccurrence' => 'Dernière réapparition: :1',

    # Début des changements pour la v4.1.2
    'invoices:converted_to_estimate' => "Facture #:1 converti en devis.",
    'global:converttoestimate' => 'Convertir en devis',
    # Fin v4.1.2

    # Début des changements pour la v4.1.3
    'tickets:view_archived' => "Voir les tickets archivés",
    'tickets:view_unarchived' => "Voir les tickets actifs",
    'tickets:archiving_ticket' => "Archiver le ticket",
    'tickets:unarchiving_ticket' => "Désarchiver le ticket",
    "tickets:unknown_error_ticket_not_altered" => "Une erreur inconnue s'est produite. Votre ticket n'a pas été modifiée.",
    # Fin v4.1.3

    # Début des changements pour la v4.1.4
    "tasks:starting_timer" => "Lancer le minuteur",
    "tasks:stopping_timer" => "Arrêter le minuteur",
    "global:all_comments" => "Tous les commentaires",
    "dashboard:view_all_comments" => "Voir tous les commentaires",
    "dashboard:latest_comments" => "Derniers Commentaires",
    "dashboard:written_by" => "Ecrit par :1 le :2",
    "dashboard:client_activity" => "Activité du client",
    "dashboard:view_all_client_activity" => "Voir toutes les activités du client",
    "dashboard:team_activity" => "Activité de l'équipe",
    "dashboard:view_all_team_activity" => "Voir toutes les activités de l'équipe",
    "dashboard:my_tasks" => "Mes tâches",
    "dashboard:view_all_my_tasks" => "Voir tous mes tâches",
    "dashboard:what_the_team_is_working_on" => "Sur quoi travaille l'équipe.",
    # Fin v4.1.4

    # Début des changements pour la v4.1.6
    "global:save_milestone" => "Enregistrer l'étape",
    "global:save_task" => "Enregistrer la tâche",
    "global:private_comment" => "Ce commentaire est privé. Votre client ne le verra pas.",
    "global:clients_cant_see_private" => "Les clients ne peuvent pas voir les commentaires privés.",
    "global:is_private" => "Privé?",
    # Fin v4.1.6

    # Début des changements pour la v4.1.7
    "tickets:disable_client" => "-- Désactiver les billets de support --",
    # Fin v4.1.7

    # Début des changements pour la v4.1.8
    "global:css" => "CSS personnalisé",
    "global:js" => "JavaScript personnalisé",
    "global:js_explanation" => "Vous pouvez utiliser jQuery à volonté. Votre code sera ajouté juste avant &lt;/body&gt;.",
    "settings:frontend_js" => "Frontend Custom JavaScript",
    "settings:backend_js" => "Backend Custom JavaScript",
    # Fin v4.1.8

    # Début des changements pour la v4.1.9
    "proposals:estimate_number_and_amount" => "Devis #:1 (:2)",
    # Fin v4.1.9

    # Début des changements pour la v4.1.10
    "clients:delete" => "Supprimer le client",
    # Fin v4.1.10

    # Début des changements pour la v4.1.11
    "global:nolongerexists" => "[N'EXISTE PLUS]",
    "global:billed_amount" => "Montant facturé",
    "global:unbilled_amount" => "Montant non facturés",
    "global:is_billed" => "Facturé",
    # Fin v4.1.11

    # Début des changements pour la v4.1.14
    "settings:year_start" => "Date de début de l'année fiscale",
    "dashboard:since_explanation" => "Depuis :1",
    # Fin v4.1.14

    # Début des changements pour la v4.1.15
    "export:invoices_csv" => "Factures (CSV)",
    # Fin v4.1.15
    
    # Début des changements pour la v4.1.17
    "projects:createdtemplate" => "Modèle de projet créé. Vous pouvez créer des projets basé sur ce modèle.",
    "projects:delete_template" => "Supprimer le modèle",
    "projects:deleted_template" => "Modèle supprimé avec succès.",
    # Fin v4.1.17
    
    # Début des changements pour la v4.1.19
    "export:expenses_csv" => "Dépenses (CSV)",
    "export:clients_csv" => "Clients (CSV)",
    "projects:expense_date" => "Date de dépenses",
    # Fin v4.1.19
    
    # Début des changements pour la v4.1.20
    "clients:can_create_support_tickets" => "Permettre au client de créer un billet de support",
    "tickets:submit_new" => "Soumettre un billet",
    "global:cancel" => "Annuler",
    "global:timers" => "Minuteurs",
    "global:more" => "Plus",
    # Fin v4.1.20
    
    # Début des changements pour la v4.1.23
    "global:search" => "Rechercher",
    "authorize:api_login_id" => "Identifiants pour l'API",
    "authorize:api_login_id_description" => "Vous trouverez ceci dans Authorize.net sous Compte > Identifiants API et clé de transaction.",
    "authorize:md5_hash" => "MD5-Hash",
    "authorize:md5_hash_description" => "Voici votre identifiant pour l'API par défaut. Vous pouvez le changer dans Authorize.net, sous Compte > MD5-Hash. Si vous voyez 'Hash Value Set: No', laissez le vide.",
    "transactions:paymentfailed" => "Erreur lors du paiement",
    "transactions:extrapaymentfailed" => "Un problème est survenu lors du traitement de votre paiement. Veuillez contacter :1 at :2 pour obtenir de l'aide.",
    # Fin v4.1.23
    
    # Début des changements pour la v4.1.24
    "projects:tracked" => "Suivi",
    "settings:accounting_type" => "Méthode de présentation",
    "settings:accrual" => "Afficher les factures selon la date de création",
    "settings:cash" => "Afficher les factures selon la date de paiement",
    "reports:selection_explanation_accrual" => "Les factures sont affichées selon leur date de création.",
    "reports:selection_explanation_cash" => "Les factures sont affichées selon leur date de paiement.\n\nLes facture non payées ou partiellement payées sont affichées selon leur date de création.",
    "invoices:partially_paid" => "Partiellement",
    # Fin v4.1.24
    
    # Début des changements pour la v4.1.27
    "global:projects_ommitted" => ":1 projets non représentés",
    "global:tasks_ommitted" => ":1 tâches non représentés",
    # Fin v4.1.27
    
    # Début des changements pour la v4.1.28
    "login:username_email" => "Nom d'utilisateur / Courriel",
    # Fin v4.1.28
    
    # Début des changements de la v4.1.29
    "global:update_available" => "Mise à jour disponible",
    #Fin v4.1.29
    
    # Début des changements de la v4.1.31
    "settings:when_new_updates_are_available" => "Lorsque les mises à jour sont disponibles",
    "settings:dont_install_just_notify_me" => "Informez-moi des mises à jour",
    "settings:install_automatically" => "Installer les mises à jour automatiquement",
    "settings:loading_update_details" => "Téléchargement des informations de mises à jour...",
    "settings:updating_please_wait" => "Mise à jour en cours, veuillez patienter. Cette page sera actualisé.",
    "settings:will_have_to_overwrite_single_file" => "Pancake devra écraser 1 fichier que vous avez modifié manuellement.",
    "settings:will_have_to_overwrite_multiple_files" => "Pancake devra écraser :1 fichier que vous avez modifié manuellement.",
    "settings:checking_for_updates" => "Recherche des mises à jour, veuillez patienter.. Cette page sera actualisé.",
    "settings:updating_please_wait" => "Mise à jour en cours, veuillez patienter. Cette page sera actualisée une fois la mise à jour terminée.",
    "settings:description" => "Enregistrez vos nouveaux paramètres avant de changer de champ ou de page.",
    "settings:business_identities" => "Identités d'affaires",
    "settings:business_name" => "Nom d'entreprise",
    "settings:new_business" => "Nouvelle entreprise",
    "settings:business_identity" => "Identité d'affaire",
    "settings:business_identity_explanation" => "L'identité d'affaire de votre client sera affiché sur chacun des courriels, PDF et des pages.",
    # Fin v4.1.31

);

/** Fin du fichier: pancake_lang.php **/
