<?php defined('BASEPATH') OR exit('No direct script access allowed');
/**
 * Pancake
 *
 * A simple, fast, self-hosted invoicing application
 *
 * @package     Pancake
 * @author      Pancake Dev Team
 * @copyright   Copyright (c) 2010, Pancake Payments
 * @license     http://pancakeapp.com/license
 * @link        http://pancakeapp.com
 * @since       Version 1.0
 */

// ------------------------------------------------------------------------

$lang = array(

    /** Global Words **/
    'global:overview'				=> 'Overview',
    'global:error'					=> 'Error',
    'global:pancakeby7am'			=> 'Pancake :1',
    'global:allrelatedmediacopyright'		=> 'Pancake and all related media is Copyright :1 :2',
    'global:insecure_action'		=> 'Insecure action was attempted but caught',
    'global:disabled_in_demo'		=> 'Some features on this page are disabled for the demo.',
    'global:estimates'				=> 'Estimates',
    'global:estimate'				=> 'Estimate',
    'global:incomplete_tasks'		=> 'Incomplete Tasks',
    'global:completed_tasks'		=> 'Completed Tasks',
    'global:projects'				=> 'Projects',
    'global:tickets'				=> 'Tickets',
    'global:project'				=> 'Project',
    'global:upload_failed'			=> 'There was a problem uploading your file. Please try again. If the problem persists, please contact support@pancakeapp.com.',
    'global:upload_not_allowed'		=> 'The file type of the file you were trying to upload is not allowed. If you need to upload a file of that type, please compress it into a .zip or any other archive format you might find appropriate.',
    'global:copied'					=> 'Copied!',
    'global:sentbutunpaid'			=> 'Outstanding (Sent but unpaid)',
    'global:task'					=> 'Task',
    'global:clients'				=> 'Clients',
    'global:access_denied'                      => "Access Denied",
    'global:users'					=> 'Users',
    'global:send_to_client'			=>  'Send to client',
    'global:couldnotsendemail'		=> 'Could not send the email.  Please check your settings.',
    'global:emailsent'				=> 'Email has been sent!',
    'global:yes'					=> 'Yes',
    'global:no'						=> 'No',
    'global:notyetsent'				=> 'Not sent to client',
    'global:dontshowagain'			=> "Don't show this again",
    'global:enable'					=> 'Enable',
    'global:is_enabled'				=> 'Enabled?',
    'global:is_completed'			=> 'Completed?',
    'global:Y'						=> 'Y',
    'global:N'						=> 'N',
    'global:notes'					=> 'Notes',
    'global:description'			=> 'Description',
    'global:backtoadmin'			=> 'Back to Admin',
    'global:type'					=> 'Type',
    'global:name'    				=>  'Name',
    'global:first_name'     		=>  'First Name',
    'global:last_name'     			=>  'Last Name',
    'global:company'    			=>  'Company',
    'global:for'    				=>  'for',
    'global:from'   				=>  'from',
    'global:phone'     				=>  'Phone',
    'global:email'      			=>  'Email',
    'global:contacts'   			=>  'Contacts',
    'global:week'					=> 'Weekly',
    'global:na'						=> 'N/A',
    'global:quarterly'				=> 'Quarterly',
    'global:every_six_months'		=> 'Every 6 months',
    'global:statistics' => "Statistics",
    'global:biyearly'				=> 'Every 2 years',
	'global:month'					=> 'Monthly',
	'global:year'					=> 'Yearly',
	'global:fax'					=>	'Fax',
	'global:mobile'					=>	'Mobile',
	'global:address'				=>	'Address',
	'global:api_key'				=> 'API Key',
	'global:website'				=>	'Website',
	'global:action'					=>	'Action',
	'global:items'					=>	'Items',
	'global:reusableinvoiceitems'	=> 'Reusable Invoice Items',
	'global:reusableinvoiceitems_description'	=> 'You should use Reusable Invoice Items when you want to reuse the same item in different invoices. To use them when you\'re creating or editing an invoice, simply start typing the name of the item you saved, and it\'ll offer to autocomplete the item\'s details for you.',
	'global:create_invoice_estimate'	=>	'Create invoices and estimates to collect money.',
	'global:createinvoice' 			=> 'Create Invoice',
	'global:paid' 					=> 'Paid',
	'global:unpaid'					=> 'Unpaid',
	'global:overdue'				=> 'Overdue',
	'global:time_entries'			=> 'Time Entries',
	'global:invoices'				=> 'Invoices',
	'global:invoice'				=>	'Invoice',
        'global:tasks' => 'Tasks',
	'global:estimate' 				=> 'Estimate',
	'global:dashboard'				=> 'Dashboard',
	'global:settings'				=> 'Settings',
	'global:plugins'				=> 'Plugins',
	'global:installed'				=> 'Installed',
	'global:changepassword'			=> 'Change Password',
	'global:logout' 				=> 'Log Out',
	'global:status'					=> 'Status',
	'global:client'					=> 'Client',
	'global:user'					=> 'User',
	'global:title'					=> 'Title',
	'global:subtitle'				=> 'Subtitle',
	'global:to'						=> 'To (separate multiple addresses with a comma)',
	'global:subject'				=> 'Subject',
	'global:thanks'					=> 'Thanks!',
	'global:proposals'				=> 'Proposals',
	'global:proposal'				=> 'Proposal',
	'global:reports'				=> 'Reports',
	'global:item'					=> 'Item',
	'global:report'					=> 'Report',
	'global:saveandinsert'			=> 'Save and Insert',
	'global:details'				=>	'Details',
	'global:license_key'			=> 'License Key',
	'global:version'				=> 'Version :1',
	'global:content'				=> 'Content',
	'global:add'					=>	'Add',
	'global:edit'					=>	'Edit',
	'global:resend'					=>	'Resend',
	'global:sent'					=> 'Sent',
	'global:not_sent'				=> 'Not sent',
	'global:view'					=>	'View',
	'global:delete'					=>	'Delete',
	'global:remove'					=>	'Remove',
	'global:sort'					=>	'Sort',
	'global:deleteitem'				=> 'Delete Item',
	'global:dragtoreorder'			=> 'Drag To Reorder',
	'global:start'					=> 'Start',
	'global:stop'					=> 'Stop',
    'global:start_timer'			=> 'Start Timer',
    'estimates:create' => "Create Estimate",
	'global:stop_timer'				=> 'Stop Timer',
	'global:created'				=>	'Created',
	'global:updated'				=>	'Updated',
	'global:update'					=>	'Update',
    'global:update_available'					=>	':1 update available',
    'global:updates_available'					=>	':1 updates available',
	'global:downloadpdf'			=> 'Download PDF',
	'global:yesdelete'				=> 'Yes, delete!',
	'global:confirm_emphisised'		=>	'There is no going back!',
	'global:color'					=> 'Color',
	'global:save'					=> 'Save',
	'global:unknown'				=> 'Unknown',
	'global:upload_ini_size'		=> 'The file you uploaded exceeds the size limit imposed by your PHP installation.',
	'global:upload_error'			=> 'A problem occurred while uploading the file. Please try again.',
	'global:recurring'				=> 'Recurring',
	'global:unsent'					=> 'Unsent',
	'global:converttoproject'		=> 'Convert to Project',
    'global:converttoinvoice'		=> 'Convert to Invoice',
	'global:viewpdf'				=> 'View PDF',
	'global:duplicate'				=> 'Duplicate',
	'global:urltosend'				=>	'Here is the url to send:',
	'global:copytoclipboard'		=>	'Copy to clipboard',
	'global:you_need_pancake_cron_job'		=> 'To use recurring invoices, you must be running the Pancake cron job.',
    'global:if_you_dont_know_how_to_set_it_up'		=> 'If you don\'t know how to set it up, <a href="http://help.pancakeapp.com/customer/portal/articles/605703">click here</a>.',
	'global:quick_links'			=> 'Quick Links',
	'global:view_all'				=> 'View All',
	'global:deleted'				=>	'Deleted',

        'global:add_more' => "Add More",
        'global:upload_files' => "Upload Files",
	'global:optional_increment'		=> '<strong>Optional</strong> - will auto increment',

	'login:ahoy'					=> 'Ahoy!',
	'login:readytodothis'			=> 'Ready to do this?',
	'login:sup'						=> 'Sup?',
	'global:actions'				=> 'Actions',
        'global:select' => "--- Select ---",

	/** Greetings **/
	'global:greetings'	=>	array('Ahoy!', 'Hello,', 'Hey,', 'Sup,'),
    
        'global:mark_as_unanswered' => 'Mark as unanswered',
        'global:mark_as_accepted' => 'Mark as accepted',
        'global:mark_as_rejected' => 'Mark as rejected',
        'global:reject_estimate' => 'Reject estimate',
        'global:accept_estimate' => 'Accept estimate',
        'global:estimate_rejected' => 'Estimate Rejected',
        "global:estimate_accepted" => "Estimate Accepted",
        'global:reject_proposal' => 'Reject proposal',
        'global:accept_proposal' => 'Accept proposal',
        'global:proposal_rejected' => 'Proposal Rejected',
        "global:proposal_accepted" => "Proposal Accepted",
        "global:client_area" => "Client Area",
        "global:admin" => "Admin",
        "global:all_settings" => "All Settings",
        'global:viewable' => 'Viewable in client area',
        'global:not_viewable' => 'Not viewable in client area',
    
	/** End Greetings **/

	/** Dashboard **/
	'dashboard:collected'		=>	'Collected',
	'dashboard:outstanding'		=>	'Outstanding',
	'dashboard:latest_activity'	=>	'Latest Activity',
        'dashboard:these_are_your_upcoming_tasks' => "These are your upcoming tasks, :1.",
	'dashboard:upcoming_tasks' 	=> 	'Upcoming Tasks',
	/** End Dashboard **/


	/** Users **/

	// ==============================
	// = LOGIN PAGE COMPLETED - Lee =
	// ==============================
	'login:forgotinstructions'	=>	'Please enter your email address so we can send you an email to reset your password.',
	'login:reset'				=>	'Reset &raquo;',
	'login:reset'				=>	'Reset Password',
	'login:username'			=>	'Username',
	'login:password'			=>	'Password',
	'login:changepassword'		=>	'Change Password',
	'login:email'				=>	'Email Address',
	'login:login'				=>	'Login',
	'login:logout'				=>	'Logout',
	'login:remember'			=>	'Remember Me',
	'login:forgot'				=>	'Forgot your password?',
	'login:cancel'				=>	'&laquo; Cancel',
	/** End Users **/

	/** User Groups **/
	'groups:edit_title'			=> 'Edit Group %s',
	'groups:add_title'			=> 'Add User Group',

	/** Clients **/
	'clients:title'				=>	'All Clients',
	'clients:filter'			=>	'Client Filter',
	'clients:add'				=>	'Add Client',
	'clients:removefilter'		=>	'Remove Filter',
	'clients:edit'				=>	'Edit Client',
	'clients:noclienttitle' 	=> 'You need to enter some clients!',
	'clients:noclientbody'		=> 	'So you can send them some invoices. Add one now?',
	'clients:noclienttitlefilter' 	=> 'No clients match your filter',
	'clients:hasnoinvoicetitle'		=>	'Sweet! This client is all set up!',
	'clients:hasnoinvoicebody'	=> 	'Let\'s create an invoice for them and get billing! Add one now?',
	'clients:added' 			=> 'The client has been added!',
	'clients:edited' 			=> 'The client has been updated!',
	'clients:deleted' 			=> 'The client has been deleted!',
	'clients:does_not_exist' 	=> 'That client does not exist!',
	'clients:health_check'		=> 	'Health Check',
	'clients:all' 				=> 'All',
	'clients:delete_title'		=>	'Delete this client?!?!',
	'clients:delete_message'	=>	'Are you sure you want to delete this client?<br />This will also delete all invoices, projects and proposals for this client.',
	'clients:clientaction'		=>	'&nbsp;',
	'clients:passphrase'		=> 'Pass Phrase',
	'clients:bad_passphrase'	=> 'Pass Phrase is incorrect.',
	'clients:total_clients'		=>	'Total Clients',
	'clients:support'			=>  'Support',
	'clients:support_rates'		=>  'Support Rates',
	'clients:edit_support_rates'		=>  'Set Rates',
	/** End Clients **/


	/** Contact Log **/
	'contact:title'				=>	'Recent Contact History',
	'contact:method'			=>	'Contact Method',
	'contact:contact'			=>	'Contact',
	'contact:subject'			=>	'Subject',
	'contact:content'			=>	'Content',
	'contact:method'			=>	'Contact Method',
	'contact:calling_title'		=>	'Calling client ":1"',
	// 'contact:view_all'		=>	'View All',
	/** End Contact Log **/

	/** Invoices **/
	'invoices:markassent'			=> 'Mark as Sent',
        'invoices:invoicedate'			=> 'Invoice Date',
        'invoices:file_name' => "File Name",
        'invoices:date_created' => "Date Created",
        'invoices:size' => "Size",
        'invoices:files' => "Files",
	'invoices:sentbutunpaid'		=> 'Invoices sent to the client but still not paid',
	'invoices:duplicated'			=> 'Duplicated invoice #:1. The new invoice\'s number is #:2.',
	'invoices:all'					=>	'All Invoices',
	'invoices:empty'				=>	'No invoices yet.',
	'invoices:overdue'				=>	'Overdue Invoices',
        'invoices:tax_collected' => "Tax Collected",
	'invoices:paid'					=>	'Paid Invoices',
	'invoices:recurringinvoices'	=> 'Recurring Invoices',
	'invoices:unsentinvoices'		=> 'Unsent Invoices',
	'invoices:unpaid'				=>	'Unpaid Invoices',
	'invoices:thisinvoicewaspaidon'	=> 'This invoice was paid on :1. Thank you!',
	'invoices:senton'				=> 'Sent on :1',
	'invoices:lastsenton'				=> 'Last sent on :1 at :2',
	'invoices:paidon'				=> 'Paid on :1',
	'invoices:paidonsingle'			=>	'Paid on',
	'invoices:thisinvoiceisunpaid'	=> "This invoice hasn't been paid yet.",
	'invoices:noinvoicetitle'		=>	'You have no invoices yet!',
        'invoices:noinvoicesforthefilteredclient' => "You have no invoices for :1.",
	'invoices:noinvoicebody'		=>	'You should create an invoice now! <br /> Clients love invoices!',
	'invoices:send_now_title'		=> 'Send invoice now?',
	'invoices:send_now_body'		=> 'Fill out the form below and we\'ll deliver this invoice for you.',
	'invoices:newinvoice'			=>	'Create Invoice',
	'invoices:send_now'				=> 'Send invoice',
	'invoices:timequantity'			=> 'Time/Quantity',
	'invoices:ratewithcurrency'		=> 'Rate (:1)',
	'invoices:taxable' 				=> 'Taxable',
	'invoices:total' 				=> 'Total',
	'invoices:amount'				=>	'Amount',
	'invoices:due'					=>	'Due',
	'invoices:subtotal'				=> 'Subtotal',
	'invoices:totaltax'				=> 'Total Tax',
	'invoices:filestodownload'		=> 'Files for Download',
	'invoices:added'				=> 'The invoice has been added!',
	'invoices:fileswillbeavailableafterpay'		=> 'These files will be available for download once the invoice has been fully paid.',
	'invoices:no_payment_gateways_enabled'		=> 'No payment gateways have been enabled, which might make it tricky to be paid. Enable in <a href=":1">Settings</a>',
	'invoices:invoicenumber'		=> 'Invoice #:1',
	'invoices:number'				=> 'Invoice #',
	'invoices:type'					=>	'Invoice Type',
	'invoices:is_recurring'			=> 'Recurring?',
	'invoices:is_paid'				=> 'Paid?',
	'invoices:is_sent'				=> 'Sent?',
	'invoices:date_entered'			=> 'Date of Creation',
	'invoices:delete_title'			=>	'Delete this invoice?',
        'items:select_time_entry' => 'Time Entry',
	'invoices:delete_message'		=>	'Are you sure you want to delete this invoice?',
	'invoices:create'				=> 'Create Invoice',
	'invoices:edit'					=> 'Edit Invoice',
	'invoices:amountrequired'		=> 'The Amount field is required',
	'invoices:currencydoesnotexist'	=> 'This currency does not exist.',
	'invoices:unique_id'			=> 'Unique ID',
	'invoices:willreoccurin'		=> 'This invoice will reoccur on :1.',
	'invoices:willbesentautomatically'		=> 'The client will be notified by email about this invoice on :1.',
	'invoices:thisisareoccurrence'		=> 'This invoice is a reoccurrence of Invoice :1.',
	'invoices:clientlastnotifiedon'		=> 'The client was notified by email about this invoice on :1.',
	'invoices:simple'				=> 'Simple',
	'invoices:simple_help'			=> 'A simple invoice has no line items. Simply a total.',
	'invoices:detailed'				=> 'Detailed',
	'invoices:detailed_help'		=> 'Detailed invoices allow you to have multiple line items.',
	'invoices:estimate_help'		=> 'Estimates are detailed invoices that are not billable.',
	'invoices:unpaid_totalamount'	=>	'Unpaid / Total amount',
	'invoices:saveinvoice'			=> 'Save Invoice',
	'invoices:deleted'				=> 'The invoice has been deleted!',
	'invoices:view'					=> 'View Invoice',
	'invoices:is_viewable'			=>	'Show in client area?',
	'invoices:no_invoices'			=> 'There are no invoices.',
	'invoices:addedsuccess'			=>	'You have added an invoice for',
	'invoices:invoice'				=>	'invoice',
	'invoices:addedconf'			=>	'You have added invoice # <strong>:1</strong>, totalling <strong>:2</strong> for :3:4.',
	'invoices:preview'				=>	'Preview Invoice',
	'invoices:editinvoice'			=>	'Edit invoice #:1',
	'invoices:messageupdated'		=>	'The invoice has been updated!',
	'invoices:resend'				=>	'Resend Invoice',
	'invoices:client_viewed'		=>	':1 viewed invoice #:2 on :3',
	'invoices:client_paid'			=>	':1 paid invoice #:2 on :3',
	'invoice:paid_amount'			=>	'Amount Paid',
	/** End Invoices **/

	/** Estimates **/
	'estimates:attachedtoproposal'		=> 'Attached to proposal #:1',
	'estimates:duplicated'			=> 'Duplicated estimate #:1. The new estimate\'s number is #:2.',
	'estimates:alltitle'			=>	'All Estimates',
	'estimates:attachingtoproposal'		=>     'Attaching estimate to proposal, please wait...',
	'estimates:delete_title'		=>	'Delete this estimate?',
	'estimates:delete_message'		=>	'Are you sure you want to delete this estimate?',
	'estimates:createnew'			=>	'Create Estimate',
	'estimates:generate_estimate'		=> 'Generate Estimate',
	'estimates:converted'			=> 'Converted estimate #:1 to a project.',
    'estimates:converted_to_invoice'			=> 'Converted estimate #:1 to an invoice.',
	'estimates:noestimatetitle'		=>	'You have no estimates',
	'estimates:noestimatesforthisclient'	=>	'You have no estimates for this client.',
        'estimates:noestimatesforthefilteredclient' => "You have no estimates for :1.",
	'estimates:deleted'				=> 'The estimate has been deleted!',
	'estimates:noestimatebody'		=>	'You should get on that! Would you like to create one now?',
	'estimates:estimatenumber'		=>	'Estimate #:1',
	'estimates:view'				=> 'View Estimate',
	'estimates:no_estimates'		=> 'There are no estimates.',
	'estimates:addedsuccess'		=>	'You have added an estimate for',
	'estimates:estimate'			=>	'estimate',
	'estimates:added'				=>	'Success! The estimate has been added.',
	'estimates:addedconf'			=>	'You have added estimate # <strong>:1</strong>, totalling <strong>:2</strong> for :3:4.',
	'estimates:send_now_title'		=> 'Send estimate now?',
	'estimates:send_now_body'		=> 'Fill out the form below and we\'ll deliver this estimate for you.',
	'estimates:send_now'			=>	'Send Estimate',
	'estimates:edit'				=>	'Edit Estimate',
	'estimates:preview'				=>	'Preview Estimate',
	'estimates:editestimate'		=>	'Edit estimate #:1',
	'estimates:messageupdated'		=>	'The estimate has been updated!',
    'estimates:client_viewed'		=>	':1 viewed estimate #:2 on :3',
	'estimates:resend'				=>	'Resend Estimate',
    'estimates:estimatedate'			=> 'Estimate Date',
	/** End Estimates **/

	/** Projects **/
    'projects:status_id'			=> 'Task Status',
    'projects:projected'			=> 'Projected',
	'projects:projected_hours'		=> 'Projected Hours',
	'projects:navigationitem'		=> 'Projects',
    'projects:hours_worked'			=> 'Number of hours worked',
	'projects:hours_worked_short'	=> 'Hours worked',
	'projects:alltitle'				=>	'All Projects',
	'projects:totalprojects'		=>	'Total Projects',
	'projects:noprojecttitle'		=> 'There are no projects yet!',
	'projects:noprojecttext'		=> 'Would you like to add one now? ',
	'projects:add'					=> 'Create Project',
	'projects:createfromtemplate'	=> 'Create from Template',
	'projects:doesnotexist'			=> 'The project you are trying to access does not exist.',
	'projects:edit'					=> 'Edit Project',
	'projects:delete'				=> 'Delete Project',
	'projects:project'				=> 'Project',
    
        'projects:new_project_from_estimate_without_number' => "New Project from Estimate",
        'projects:new_project_from_estimate_with_number' => "New Project from Estimate #:1",
    
	'projects:due_date'				=> 'Due Date',
	'projects:is_completed'			=> 'Completed?',
	'projects:manage_project'		=> 'Manage Project',
	'projects:areyousuredeletetask'	=> 'Are you sure you want to delete this task?',
	'projects:add_time'				=> 'Add Time Entry',
    'projects:add_hours'			=> 'Add Hours',
	'projects:generate_invoice'		=> 'Generate Invoice',
	'projects:no_projects'			=> 'There are no projects.',
	'projects:archive_proj'			=> 'Archive Project',
	'projects:unarchive_proj'		=> 'Un-archive Project',
	'projects:archive'				=> 'View Archive',
	'projects:active'				=> 'Active Projects',
	'projects:archived'				=> 'Archived Projects',
	'projects:noarchivedprojecttitle'		=> 'You have no archived projects.',
	'projects:noarchivedprojecttext'		=> 'You can archive a project from your project page ',
	'projects:allarchivedtitle'		=>	'All Archived Projects',
	'projects:templatize'			=>	'Save as template',
	/** End Projects **/


	/** Milestones **/
	'milestones:add'				=> 'Add Milestone',
	'milestones:edit'				=> 'Edit Milestone',
	'milestones:delete'				=> 'Delete Milestone',
	'milestones:milestone'			=> 'Milestone',
	'milestones:target_date'		=> 'Target Date',
	'milestones:assigned_user'		=> 'Assigned User',
	'milestones:select_default'		=> '-- No milestone --',
	'milestones:no_milestone'		=> 'Tasks without Milestone',
	'milestones:add_success'		=> 'Milestone ":1" added successfully!',
    'milestones:edit_success'		=> 'Milestone ":1" edited successfully!',
    'milestones:add_failed'			=> 'Milestone ":1" could not be edited.',
    'milestones:edit_failed'		=> 'Milestone ":1" could not be added.',
    'milestones:are_you_sure_delete'		=> 'Are you sure you want to delete this milestone?',
    'milestones:delete_success'		=> 'Milestone ":1" deleted successfully!',
    'milestones:does_not_exist'		=> 'This milestone does not exist.',
    'milestones:target_date'		=>  'Target Date',
    'milestones:select_assignee_default'	=> 'No Assignee',
    /** End Milestones **/

    /** Proposals **/
    'proposal:outline'  =>  'Proposal Outline',


    /** End Proposals **/

	/** Reminders **/

	'reminders:reminders'	=>	'Reminders',
	'reminders:send'		=>	'Send Reminders',
	'reminders:success'		=>	'Those reminders have been sent!!',
	'reminders:remind'		=>  'Remind',
	'reminders:message'		=>	'Message',
	'reminders:due'			=>	'Days',
	'reminders:details'		=>	'Details',
	'reminders:log'			=>	'Log',

	/** End Reminders **/


	/** Email Templates **/
	'emailtemplates:email_templates'	=>  'Email Templates',
	'emailtemplates:create_template'	=>	'Create new template',
	'emailtemplates:add'				=>	'Create new email template',
	'emailtemplates:edit'				=>	'Edit email template',
	'emailtemplates:manage'				=>	'Manage Templates',
	'emailtemplates:name'				=>	'Email Name',
	'emailtemplates:subject'			=>	'Email Subject',
	'emailtemplates:days'				=>	'Day Range',
	'emailtemplates:type'				=>	'Template Type',
	'emailtemplates:success'			=>	'Successfully created email template',
	'emailtemplates:edited'				=>	'Successfully edited email template',
	'emailtemplates:does_not_exist'		=>	'Email template does not exist',
	'emailtemplates:deleted'			=>	'Email template successfully deleted',
	'emailtemplates:delete_title'		=>	'Delete email template',
	'emailtemplates:delete_message'		=>	'Are you sure you\'d like to delete this email template?',


	/** End Email Templates **/

    /** Reports **/
    'reports:perclient'		=> 'per client',
    'reports:datefrom'		=> 'From',
    'reports:allclients'	=> 'All clients',
    'reports:dateto'		=> 'To',
    'reports:byclient'		=> 'Client',

    'reports:view'			=> 'View Report',
    'reports:show_all'		=> 'Show Reports',
    
    'reports:paid_and_unpaid' => "Paid and Unpaid",
    'reports:paid_vs_unpaid_over_time' => "Paid vs. Unpaid over time",
    'reports:per_client' => 'per client',
    'reports:total_with_tax' => "Total (w/ tax)",
    'reports:total_without_tax' => "Total (no tax)",
    'reports:total_collected' => 'Total Collected',
    'reports:fees_paid' => 'Fees Paid',
    'reports:total_amount' => 'Total Amount',
    'reports:paid_amount' => "Paid Amount",
    'reports:unpaid_amount' => "Unpaid Amount",
    'reports:client_name' => "Client Name",
    'reports:filters' => 'Filters',
    'reports:selection_explanation' => 'Unpaid invoices are shown based on their due date. 
Paid invoices are shown based on their payment date.
Invoices with more than one payment part are shown based on the payment date of the first part.
Unpaid invoices with no due date are shown based on the date they were created.',
    
    'reports:nodata'		=> 'No :1.',
    /** End Reports **/

    /** Currencies **/
    'currencies:default'	=> '[Default] :1',
    'currencies:cad'		=> 'Canadian Dollar',
    'currencies:eur'		=> 'Euro',
    'currencies:usd'		=> 'U.S. Dollar',
    'currencies:gbp'		=> 'Pound Sterling',
    'currencies:hkd'		=> 'Hong Kong Dollar',
    'currencies:php'		=> 'Philippine Peso',
    'currencies:zar'		=> 'South Africa, Rand',
    /** End Currencies **/

    /** Proposals **/
    'proposals:duplicated'				=> 'Duplicated proposal #:1. The new proposal\'s number is #:2.',
    'proposals:usesectiontemplate'		=> 'Use this Section Template',
    'proposals:showcontents'			=> 'Show Contents',
    'proposals:hidecontents'			=> 'Hide Contents',
    'proposals:deletepremadesection'	=> 'Delete Section Template',
    'proposals:nopremadesections'		=> 'You have no saved section templates.',
    'proposals:newproposal'				=> 'New Proposal',
    'proposals:estimatexfory'			=> 'Estimate #:1 - :2',
    'proposals:number'					=> 'Proposal #',
    'proposals:all'						=> 'All Proposals',
    'proposals:noproposaltitle'			=> "There are no proposals!",
    'proposals:noproposalbody'			=> "You should create a proposal now. Definitely.",
    'proposals:rejected'				=> 'Rejected on :1',
    'proposals:accepted'				=> 'Accepted on :1',
    'proposals:lastviewed'				=> 'Last viewed by the client on :1, at :2.',
    'proposals:neverviewed'				=> 'not viewed by the client.',
    'proposals:noanswer'				=> 'No answer',
    'proposals:createproposal'			=> 'Create Proposal',
    'proposals:editproposal'			=> 'Edit Proposal',
    'proposals:createdsuccessfully'		=> 'Proposal created!',
    'proposals:sections'				=> 'Sections',
    'proposals:section'					=> 'Section',
    'proposals:createsection'			=> 'Add New Section',
    'proposals:createpage'				=> 'Add Page',
    'proposals:emptysection'			=> '(no title)',
    'proposals:emptycontents'			=> '(no contents)',
    'proposals:emptysubtitle'			=> '(no subtitle)',
    'proposals:for'						=> 'Proposal for:',
    'proposals:pagexofcount'			=> 'Page :1 of :2',
    'proposals:saving'					=> 'Saving...',
    'proposals:save'					=> 'Save Proposal',
    'proposals:savepremade'				=> 'Save as Section Template',
    'proposals:addestimate'				=> 'Add Estimate',
    'proposals:saved'					=> 'Saved!',
    'proposals:createandedit'			=> 'Next: Edit proposal contents',
    'proposals:delete_message'			=> 'Are you sure you want to delete this proposal?',
    'proposals:createpremadesection'	=> 'Add from Section Template',
    'proposals:selected_attachments'	=> 'Select Estimate',
    'proposals:attach_selected_estimate'		=> 'Attach Selected Estimate',
    'proposals:proposal'				=> 'Proposal',
    'proposals:status'					=> 'Status',
    'proposals:view'					=> 'View Proposal',
    'proposals:estimate'				=> 'Estimate',
    'proposals:no_proposals'			=> 'There are no proposals.',
    'proposals:proposal_title' => 'Proposal Title',
    'proposals:kitchennotice'			=> 'Note: Proposals will appear in the :1 once the client has viewed the proposal link. This means you can edit it all you want and the client wont see it until you want them too.',
    /** End Proposals **/

    /** Tasks **/
    'tasks:task'						=> 'Task',
    'tasks:edit_succeeded'				=> 'Edited task successfully.',
    'tasks:hours'						=> 'Hours',
    'tasks:due_date'					=> 'Due Date',
    'tasks:is_completed'				=> 'Completed?',
    'tasks:timer'						=> 'Timer',
    'tasks:rate'						=> 'Rate',
    'tasks:default_rate'				=> 'Default Rate',
    'tasks:entries'						=> 'Time Entries',
	'tasks:view_entries'				=> 'View Entries',
    'tasks:edit_entry'					=> 'Edit Time Entry',
	'tasks:create'						=> "Add Task",
	'tasks:create_sub'					=> "Add Sub-Task",
	'tasks:task_parent'					=> "Task Parent",
	'tasks:edit'						=> "Edit Task",
	'tasks:create_succeeded'			=> "The task has been created!",
	'tasks:no_task_title'				=> 'Hmm, no tasks yet...',
    'tasks:no_task' => "No Task",
	'tasks:no_task_message'				=> 'You should create some!',
	'tasks:is_viewable'					=> 'Viewable in client area?',
	'tasks:no_milestones'				=> 'Tasks with no milestones',
    'tasks:not_related_to_a_task'		=> "-- Not related to a task --",
    'tasks:select_parent_default'		=> '-- No parent task --',
	'tasks:timers_running'				=>	'Timers Running',
	'tasks:task_completed_by'			=>	':1 completed task :2 at :3',
	'tasks:discussion'					=>	'Discussion: ',
'tasks:billed_hours' => "Billed Hours",
    'tasks:unbilled_hours' => "Unbilled Hours",
    
    
	/** Users **/
	'users:create_user'					=> 'Create User',
        'users:confirm_delete_emphasised' => "There is no going back!",

	/** Items **/
	'items:name'						=> 'Item Name',
	'items:description'					=> 'Item Description',
	'items:qty_hrs'						=> 'Qty / Hrs',
	'items:quantity'					=> 'Quantity',
	'items:rate'						=> 'Rate',
	'items:tax_rate'					=> 'Tax Rate',
	'items:cost'						=> 'Cost',
	'items:line_items'					=> 'Line Items',
	'items:add'							=> 'Add Item',
	'items:edit'						=> 'Edit Item',
	'items:noitemtitle'					=>	'You have no items yet!',
	'items:noitembody'					=>	'You should add some items now, it makes creating invoices loads easier!',
	'items:delete_title'				=>	'Delete this item?',
	'items:delete_message'				=>	'Are you sure you want to delete item ":1"?',
	'items:type'						=> 'Type',
	'items:select_standard'				=> 'Standard',
	'items:select_expense'				=> 'Expense',
	'items:add_expense_to_project'		=> 'Add Expense',
	'items:expenses'					=> 'Expenses',
	/** END Items **/

	/** Expenses **/
	'expenses:expenses'					=>	'Expenses',
	'expenses:add'						=>	'Add Expense',
	'expenses:edit_expense'				=>	'Edit Expense',
	'expenses:delete'					=>	'Delete Expense',
	'expenses:deleted'					=>	'Expense Deleted',
	'expenses:all'						=>	'All Expenses',
	'expenses:amount'					=>	'Amount',
	'expenses:supplier'					=>	'Supplier',
	'expenses:suppliers'				=>	'Suppliers',
	'expenses:category'					=>	'Category',
	'expenses:categories'				=>	'Categories',
	'expenses:add_supplier'				=>	'Add Supplier',
	'expenses:edit_supplier'			=>	'Edit Supplier',
	'expenses:add_category'				=>	'Add Category',
	'expenses:edit_category'			=>	'Edit Category',
	'expenses:parent_category'			=>	'Parent Category',
	'expenses:filter'					=>	'Filter Expenses',
	'expenses:start_date'				=>	'Start Date',
	'expenses:end_date'					=>	'End Date',


	/** END Expenses **/

	/** Transactions **/
	'transactions:paymentcancelled'				=> 'Payment Cancelled',
	'transactions:extrapaymentcancelled'		=> 'Your payment has been cancelled.',
	'transactions:paymentreceived'				=> 'Payment Received!',
	'transactions:fee_applied'					=> 'As :1 imposes a transactional fee, we have added a :2% surcharge.',
	'transactions:orderbeingprocessed'			=> 'Please wait, your order is being processed and you will be redirected to the :1 website.',
	'transactions:ifyouarenotredirected'		=> 'If you are not automatically redirected to :1 within 5 seconds...',
	'transactions:thankyouforyourpayment'		=> 'Thank you for your payment. You should be receiving a receipt via email shortly.',
	'transactions:ifyouhavefilesyouwillgetanemail'		=> 'If you have files awaiting delivery you will receive an email with a link to download them shortly.',
	'transactions:ifyoudonotreceiveemail'		=> 'If you do not receive an email within an hour please contact :1',
	/** End Transactions **/

	/** Timesheets **/
	'timesheet:taskname'			=> 'Task Name',
	'timesheet:starttime'			=> 'Start Time',
	'timesheet:endtime'				=> 'End Time',
	'timesheet:timeframe'			=> 'Timeframe',
	'timesheet:duration'			=> 'Duration',
	'timesheet:date'				=> 'Date',
	'timesheet:forproject'			=> 'Timesheet for Project ":1"',
	'timesheet:timesheet'			=> 'Timesheet',
	'timesheet:for'					=> 'Timesheet for:',
	'timesheet:totalbillable'		=> 'Total Billable Hours',
	'timesheet:view_pdf'			=> 'View Timesheet',
	'timesheet:user'			    => 'User',
	'timesheet:entries'			    => 'Entries',
        'timesheet:no_entries'                  => "There are no time entries.",
	/** End Timesheets **/


	/** Support Tickets **/

	'tickets:all_tickets'			=>	'Support Tickets',
        'tickets:support_tickets' => "Support Tickets",
	'tickets:pending'				=>	'Pending',
	'tickets:open'					=>	'Open',
	'tickets:resolved'				=>	'Resolved',
	'tickets:closed'				=>	'closed',
	'tickets:respond'				=>	'Respond to ticket',
	'tickets:ticket_options'		=>	'Ticket Options',
	'tickets:attachment'			=>	'Attachment',
	'tickets:updated_status'		=>	':1 updated the ticket status to :2',
        'tickets:add_a_new_ticket' => "Add a New Ticket",
        'tickets:create_a_new_ticket' => 'Create a New Ticket',
        'tickets:add_ticket' => 'Add Ticket',
        'tickets:assign_to_user' => 'Assign To User',
        'tickets:select_client' => 'Select Client',
        'tickets:ticket_subject' => 'Ticket Subject',
        'tickets:ticket_message' => 'Ticket Message',
        'tickets:ticket_priority' => 'Ticket Priority',
        'tickets:ticket_status' => 'Ticket Status',
        'tickets:no_priority' => '-- No priority --',
        'tickets:no_status' => '-- No status --',
        'tickets:no_posts' => "No message.",

	/** End Support Tickets **/

	/** Frontend **/
	'frontend:hithere'						=> 'Hi There!',
	'frontend:followthemaillinkdude'		=> 'In order to view your invoice you must click the entire link sent in the email you received. Eg :1.',
	'frontend:contactadminforassistance'	=> 'Please do so or contact :1 @ :2 for assistance',
	/** End Frontend **/

	/** Settings **/

    'settings:task_statuses'						=> "Task Statuses",
    'settings:ticket_statuses'						=> "Ticket Statuses",
    'settings:ticket_priorities'					=> "Ticket Priorities",
    'settings:background_color'						=> "Background Color",
    'settings:text_color'							=> "Text Color",
    'settings:text_shadow'							=> "Text Shadow",
    'settings:box_shadow'							=> "Box Shadow",
    'settings:default_rate'							=> "Default Rate",
    'settings:allowed_extensions'					=> 'Allowed Upload Extensions',
    'settings:comma_separated'						=> 'comma-separated',
    'settings:pdf_page_size'						=> 'PDF Page Size',
    'settings:default_invoice_notes'				=> 'Default Invoice Notes',
    'settings:default_invoice_title'				=> 'Default Invoice Title',
    'settings:default_invoice_due_date'				=> 'Default Due Date',
    'settings:autosave_proposals'					=> 'Autosave Proposals',
    'settings:default_invoice_due_date_explain'		=> 'days after invoice is created. If you don\'t want a default date, leave this empty.',
    'settings:testemailsettings'					=> 'Test Email Settings',
    'settings:kitchen_route'						=> 'Client Access Link Prefix',
    'settings:kitchen_route_explain'				=> "(Preview: :1)",
    'settings:include_remittance_slip'				=> 'Remittance Slips',
    'settings:include_remittance_slip_explain'		=> "If checked, invoice PDFs will include a remittance slip.",
    'settings:items_per_page'						=> 'Items Per Page',
    'settings:items_per_page_explain'				=> 'Number of items (invoices/estimates/proposals/projects/tasks) to show per page.',
    'settings:send_x_days_before'					=> 'Default "send days before"',
    'settings:send_x_days_before_explain'			=> "Default number of days before a recurring invoice is due to send it to a client.",
    'settings:file_to_import'						=> 'File To Import',
    'settings:export_types'							=> 'Pancake exports everything in JSON format.',
    'settings:file_should_be_csv'					=> 'Pancake will automatically process your file and import everything in it. If Pancake is unable to process your file, it will let you know, and it will give you the option to send us some information to help us make Pancake work with your file.',
    'settings:importnow'							=> 'Import now!',
    'settings:whatimporting'						=> 'What are you importing?',
    'settings:whatexporting'						=> 'What are you exporting?',
    'settings:nouploadedimportfile'					=> 'You did not upload a file to import.',
    'settings:import'								=> 'Import (BETA)',
    'settings:importedclients'						=> 'Imported :1 clients successfully.',
    'settings:importedprojects'                                         => "Imported :1 projects successfully.",
    'settings:importedusers'                                            => "Imported :1 users successfully.",
    'settings:importedinvoices'						=> 'Imported :1 invoices successfully.',
    'settings:importedtasks'						=> 'Imported :1 tasks successfully.',
    'settings:importedestimates' => 'Imported :1 estimates successfully.',
    'settings:importedtime_entries'					=> 'Imported :1 time entries successfully.',
    'settings:xwereduplicates'						=> ':1 were duplicates, and were ignored.',
    'settings:import_desc'							=> 'Import data into Pancake.',
    'settings:export'								=> 'Export',
    'settings:exportnow'							=> 'Export now!',
    'settings:importexport'							=> 'Import / Export',
    'settings:removelogo'							=> 'Remove Logo',
    'settings:wrong_license_key'					=> 'The license key you have entered is not valid.',
    'settings:noopenssl'							=> 'Your PHP server does not have OpenSSL configured, which means you can\'t use Gmail or Google Apps for sending email. Please contact your host and let them know you need OpenSSL.',
    'settings:logoremoved'							=> 'Logo removed successfully!',
    'settings:save'									=> 'Save Settings',
    'settings:logodimensions'						=> 'The logo should be 240 pixels wide and 106 pixels tall.',
    'settings:logoformatsallowed'					=> 'BMP, PNG, JPG (JPEG) and GIF are allowed.',
    'settings:ftp_user'								=> 'FTP User',
    'settings:ftp_pass'								=> 'FTP Password',
    'settings:ftp_path'								=> 'FTP Path',
    'settings:ftp_port'								=> 'FTP Port',
    'settings:ftp_pasv'								=> 'Passive Mode?',
    'settings:nophpupdates'							=> "Because of the way your server is configured, you need to enter your FTP details so that Pancake can update itself. These details are used internally by Pancake and are never transmitted to anyone.",
    'settings:ftp_host'								=> 'FTP Host',
    'settings:uptodate'								=> 'Pancake is up to date (:1)',
    'settings:newversionavailable'					=> 'There is a new version of Pancake available (:1)!',
    'settings:updatenow'							=> 'Update now!',
    'settings:checkforupdates' => "Check for updates",
    'settings:youneedtoconfigurefirst'				=> 'Your Pancake is not yet configured to update itself. Please enter your FTP details below, then press "Save Settings".<br /> Pancake will then let you update.',
    'settings:general'								=> 'General',
    'settings:emails'						=> 'Emails',
    'settings:taxes'								=> 'Taxes',
    'settings:currencies'							=> 'Currencies',
    'settings:branding'								=> 'Branding',
    'settings:payment_methods'						=> 'Payments',
    'settings:feeds'								=> 'Feeds',
    'settings:api_keys'								=> 'API Keys',

    'settings:time_entry_times' => "Time Entry Times",
    "settings:include_dates_and_times_in_line_items" => 'Include dates and times in "Time Entry" line item descriptions.',
    "settings:when_generating_invoice" => "When generating invoices, use a line item per",
    "settings:use_utf8_font" => "Use UTF-8 font in PDFs",
    "settings:use_utf8_font_explanation" => "Use this if characters are broken in your PDFs.",
    "settings:pdf_attachments" => "PDF Attachments",
    "settings:pdf_attachments_explanation" => "If checked, Pancake will attach the corresponding PDF to invoice, estimate or proposal emails.",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    
    
    
    'settings:site_name'			=> 'Site name',
    'settings:language'				=> 'Language',
    'settings:timezone'				=> 'Timezone',
    'settings:notify_email'			=> 'Notify email',
    'settings:currency'				=> 'Currency',
    'settings:theme'				=> 'Frontend Theme',
    'settings:admin_theme'			=> 'Admin Theme',
    'settings:admin_name'			=> 'Admin name',
    'settings:date_format'			=> 'Date Format',
    'settings:time_format' => "Time Format",
    'settings:task_time_interval'	=> 'Time Entry Rounding (Leave empty for no rounding)',
    'settings:task_time_interval_description' => '(eg. 00:30 or 0.5 - all time entries are rounded up to the nearest 00:30 when billing for them in an invoice.)',
    'settings:mailing_address'		=> 'Mailing Address',

    'settings:default_subject'			=> 'Default Subject',
    'settings:default_contents'			=> 'Default Message',
    'settings:new_estimate'				=> 'New Estimate',
    'settings:new_invoice'				=> 'New Invoice',
    'settings:new_proposal'				=> 'New Proposal',
    'settings:paid_notification'		=> 'Paid Notification',
    'settings:payment_receipt'			=> 'Payment Receipt',
    'settings:new_ticket'				=> 'New Ticket',
    'settings:ticket_invoice'			=> "New Ticket Invoice",
    'settings:ticket_updated'			=> 'Ticket Updated',
    'settings:ticket_status_updated'	=> 'Ticket Status Updated',

    'settings:logo'					=> 'Your logo',
    'settings:frontend_css'			=> 'Frontend Custom CSS',
    'settings:backend_css'			=> 'Backend Custom CSS',

    'settings:rss_password'			=> 'RSS Password',
    'settings:default_feeds'		=> 'Default Feeds',
    'settings:cron_job_feed'		=> 'Cron Job',
    'settings:feed_generator'		=> 'Feed Generator',
    'settings:your_link'			=> 'Your Link',
    'settings:bcc'					=> 'BCC',
    'settings:automaticallybccclientemail'		=> 'Automatically send a copy of all client emails to the notify email (defined above)',
    'settings:api_note'				=> 'Name / Note',
    'settings:api_key'				=> 'Key',

    'settings:tax_name'				=> 'Tax Name',
    'settings:tax_value'			=> 'Value',
    'settings:tax_reg'				=> 'Registration / Code',
    'settings:add_tax'				=> 'Add Another Tax',

    'settings:currency_name'		=> 'Currency Name',
    'settings:currency_code'		=> 'Currency Code',
    'settings:exchange_rate'		=> 'Exchange Rate',
    'settings:add_currency'			=> 'Add Another Currency',
    /** End Settings **/

    'update:ifyourenotsurecontactus'		=> "If you're not sure what to do, please <a href='http://pancakeapp.com/forums/newtopic/2/'>start a new tech support topic in the forums</a>.",
    'update:youmodified'					=> 'You modified',
    'update:youdeleted'						=> 'You deleted',
    'update:loadingpleasewait'				=> 'Loading, please wait...',
    'update:errordownloading'				=> 'An update to Pancake is available, but Pancake is having problems downloading it.',
    'update:herearestepstofix'				=> 'Here are a few steps you can try to fix it:',
    'update:makesureuploadsiswritable'		=> 'Make sure that your uploads folder is writable (CHMOD 0777).',
    'update:deletepancakesystemupdate'		=> 'Delete the pancake-update-system folder (inside the uploads folder), and all its contents.',
    'update:loadpancakeagain'				=> "Load Pancake again. If the error persists, change the owner of the Pancake folder (chown) so it matches the web server's user. If you can't do that, or don't know how to, please send an email to support@pancakeapp.com, and we'll help you.",
    'update:whatschanged'					=> "What's new in :1",
    'update:ftp_conn'						=> 'Pancake could not connect to the FTP host.',
    'update:ftp_login'						=> 'Pancake could not login via FTP (wrong FTP username/password?).',
    'update:ftp_chdir'						=> 'Pancake could not set the FTP path (path probably does not exist).',
    'update:ftp_no_uploads'					=> 'Pancake could not obtain permission to upload files via FTP.',
    'update:ftp_indexwrong'					=> 'The FTP Path you entered is incorrect. It should be the path to Pancake\'s directory.',
    'update:ftp_indexnotfound'				=> 'The FTP Path you entered is incorrect. It should be the path to Pancake\'s directory.',
    'update:update_conflict'				=> 'You modified some files since the last update. In order to safeguard your customizations, here is a list of files that you have modified, that conflict with the latest upgrade.',
    'update:update_no_perms'				=> 'Pancake does not have enough permissions to update itself, nor does it have access to an FTP account from which it can update itself. Update cannot continue.',
    'update:review_files'					=> 'Please review these files and make backups of them before proceeding. When the upgrade is finished, you will have to re-integrate your modifications back into them. Please do not just replace the updated files with your outdated modified copies, as that may break Pancake.',
    'update:internetissues'					=> "Pancake is unable to connect to the Internet.",
    'update:pancakeneedsinternet'			=> 'For Pancake to function correctly, your server must allow it to fetch some information from the Internet (port 80).',
    'update:maybefirewall'					=> "It appears that your server is blocking Pancake from accessing the Internet. This could be a firewall issue in your server. Please contact your host for help. Ask them to allow PHP to access :1.",
    'update:nointernetaccess'				=> 'No Internet Access',
    'update:pancakeupdated'					=> 'Pancake was upgraded from :1 to :2',
    /** Action Logger  **/

    /** End Action Logger **/

    /** Partial Payments **/
    'partial:partialpayments'			=> 'Payment Plan',
    'partial:totalamounttobepaid'		=> "Total amount to be paid by the client",
    'partial:amountlefttobeadded'		=> "Amount left to be added to the payment plan",
    'partial:amounttoobig'				=> "Amount that needs to be removed from the payment plan",
    'partial:noamountneeded'			=> "Your payment plan is complete.",
    'partial:amount'        			=> 'Amount',
    'partial:add_payment'				=> 'Add Payment',
    'partial:dueon'         			=> 'Due on',
    'partial:addanother'     			=> 'Add another part to this payment',
    'partial:disabledforrecurring'		=> 'Recurring invoices are limited to one part payments',
    'partial:paymentdetails'			=> 'Payment Details',
    'partial:wrongtotal'				=> 'The sum of all the parts of your payment plan does not match the total amount you are invoicing.',
    'partial:problemsaving'				=> 'A problem occurred while saving the payment plan. Please try again.',
    'partial:wrongtotalbutsaved'		=> 'The sum of all the parts of your payment plan does not match the total amount you are invoicing.<br />The changes to your invoice were saved, but you need to fix your payment plan.',
    'partial:problemsavingbutsaved'		=> 'A problem occurred while saving the payment plan. Please try again.<br />The changes to your invoice were saved, it is only the payment plan that wasn\'t.',
    'partial:savepaymentdetails'		=> 'Save payment details',
    'partial:partpaidthanks'			=> "This part of your invoice's payment has been paid. Thank You.",
    'partial:proceedtopayment'			=> 'Proceed to payment',
    'partial:topaynowgoto'				=> 'To pay now, please go to :1',
    'partial:pay_part_x_now' => "Pay part #:1 of your invoice now",
    'partial:dueondate'					=> 'due on :1',
    'partial:paymentmethod'				=> 'Payment Method',
    'partial:paymentdate'				=> 'Payment Date',
    'partial:paymentstatus'				=> 'Payment Status',
    'partial:transactionid'				=> 'Transaction ID',
    'partial:markaspaid'				=> 'Mark as Paid',
    'partial:transactionfee'			=> 'Transaction Fee',
    /** End Partial Payments **/

    /** Payment Gateways **/
    'paypal:clickhere'					=> 'Click Here to Proceed',
    'authorize:transaction_key'			=> 'Transaction Key',
    'paypal:email'   					=> 'PayPal Email',
    'paypal:fee'    					=> 'PayPal Fee (%)',
    'paypalpro:paypalpro'				=> 'PayPal Payments Pro (BETA)',
    'paypalpro:viacreditcard'			=> 'Pay via Credit Card',
    'cash:cash'							=> 'Cash',
    'check:check'						=> 'Check',
    'moneyorder:moneyorder'				=> 'Money Order',
    'creditcard:creditcard'				=> 'Credit Card',
    'banktransfer:banktransfer'			=> 'Bank Transfer',
    'gateways:errorupdating'			=> 'There was an error updating your payment method settings.  Please contact support.',
    'gateways:paymentmethods'			=> 'Payment Methods',
    'gateways:selectpaymentmethod'		=> 'Select Payment Method',
    'gateways:nogatewayused'			=> 'No method used: Part is unpaid',
    'gateways:completed'				=> 'Completed',
    'gateways:refunded'					=> 'Refunded',
    'gateways:unpaid'					=> 'Unpaid',
    'gateways:paymentrejected'			=> ':1 Payment Rejected',
    'gateways:rejectedemail'			=> 'Pancake was notified about a :1 payment that one of your clients (:2) made, but :1 rejected it.',
    'gateways:pending'					=> 'Pending',
    'gateways:returntowebsite'			=> 'Return to :1',
    'gateways:cc_type'					=> 'Credit Card Type',
    'gateways:cc_number'				=> 'Credit Card Number',
    'gateways:cc_exp'					=> 'Expiry Date',
	'gateways:cc_cardholder'			=> 'Name on card',
    'gateways:cc_code'					=> 'CVV Code',
    'gateways:payment_details'			=> 'Payment Details',
    'gateways:api_signature'			=> 'API Signature',
    'gateways:api_password'				=> 'API Password',
    'gateways:api_username'				=> 'API Username',
    /** End Payment Gateways **/

    /** Kitchen Area **/
    'kitchen:edit_comment'				=> 'Edit Comment',
    'kitchen:add_a_comment' => "Add a comment",
    'kitchen:kitchen_name' 				=>  'Client Access Area',
    'kitchen:pleaselogin' 				=>  'Please enter your Pass Phrase to access your account',
    'kitchen:nocomments'    			=>  'There are no comments yet.',
    'kitchen:comment'   				=>  'Comment',
    'kitchen:comments'  				=>  'Comments',
    'kitchen:comments_x'                            => 'Comments (:1)',
    'kitchen:file'  					=>  'File',
    'kitchen:submitcomment'				=>  'Add comment',
    'kitchen:attachment'    			=>  'Attachment',
    'kitchen:saidon'    				=>  'said on :1, at :2',
    'kitchen:subjectinvoice'			=> 'New comment for Invoice #',
    'kitchen:subjectestimate'			=> 'New comment for Estimate #',
    'kitchen:subjectproject'			=> 'New comment for Project:',
    'kitchen:subjecttask'				=> 'New comment for Task:',
    'kitchen:subjectproposal'			=> 'New comment for Proposal:',
    'kitchen:backtodashboard'   		=>  'Back to Dashboard',
    'kitchen:client_welcome'    		=>  'Client access area for:',
    'kitchen:urltosend'					=>  'Client access url',
    'kitchen:nopassphrase'  			=>  'Currently the client "Passphrase" is not set, this means that just accessing that url is all that is needed to view the client area. If you\'d like to secure it using a simple passphrase please edit this client and set one.',
    'kitchen:passphraseset'				=>  'This client has a Passphrase set up',
    'kitchen:passphrase'    			=>  'Passphrase',
    'kitchen:description'   			=>  'This is the url to send to your client to allow them to access the client access area where they can view items, such as projects and invoices, that you have made viewable.',
	'kitchen:people_in_discussion'		=>  'People chatting',
    
    'kitchen:latest_invoice' => 'Latest Invoice',
    'kitchen:unpaid_balance' => 'Unpaid Balance: :1',
    'kitchen:total_paid_to_date' => 'Total Paid To Date: :1',

    /** END Kitchen Area **/

    'store:store' => 'Store',
    'store:buy' => "Buy ($:1)",
    'store:update' => "Update",
    'store:install' => "Install",
    'store:settings' => "Settings",
    'store:already_bought' => "You've already purchased this item!",
    'store:installed_successfully' => "You've installed the :1 :2 successfully.",
    'store:plugin' => "Plugin",
    'store:payment_gateway' => "Payment Gateway",
    'store:frontend_theme' => "Frontend Theme",
    'store:backend_theme' => "Backend Theme",
    'store:unknown' => "Unknown",
    'store:updatestoreitems' => "Update store items",
    'store:download_free' => "Download (FREE)",
    'store:error1000' => "Your authorization token is no longer valid. You will have to enter your payment details in pancakeapp.com once more.",
    'store:error1001' => "You have already purchased this store item!",
    'store:error1002' => "A problem occurred while trying to charge your credit card. Try again later.",
    'store:error1003' => "You have made an invalid request.",
    
    'email_templates:new_invoice' => 'New Invoice',
    'email_templates:new_estimate' => 'New Estimate',
    'email_templates:new_proposal' => 'New Proposal',
    'email_templates:invoice_payment_notification_for_admin' => 'Payment Notification (sent to admin)',
    'email_templates:invoice_payment_notification_for_client' => 'Payment Receipt Notification (sent to client)',
    'email_templates:new_ticket' => 'New Ticket',
    'email_templates:new_ticket_invoice' => 'New Ticket Invoice',
    'email_templates:ticket_updated' => 'Ticket Update Notification',
    'email_templates:ticket_status_updated' => 'Ticket Status Update Notification',
    'email_templates:assigned_to_task' => "Task Assignment Notification",
    'email_templates:assigned_to_milestone' => "Milestone Assignment Notification",
    'email_templates:new_comment' => "New Comment Notification"
    
    
    /** Dashboard **/


	/** END Dashboard **/
);

/** End of file: pancake_lang.php **/